type Integer = int;
type Boolean = bool;
type HeapType = <a>[ref,Field (a)]a;
type MaskType = <a>[ref,Field (a)][PermissionComponent]int;
type CreditsType = [ref]int;
type ArgSeq = <T>[int]T;
type string = int;
type Field m0;
type ref;
type PermissionComponent;
type PartialHeapType;
type ModuleName;
type TypeName;
type Mu;
type Seq m0;
const null : ref;
const unique perm$R : PermissionComponent;
const unique perm$N : PermissionComponent;
const Permission$denominator : int;
const Permission$FullFraction : int;
const Permission$Zero : [PermissionComponent]int;
const Permission$Full : [PermissionComponent]int;
const ZeroMask : MaskType;
const unique joinable : Field (int);
const unique token#t : TypeName;
const unique forkK : Field (int);
const channelK : int;
const monitorK : int;
const predicateK : int;
const emptyPartialHeap : PartialHeapType;
const CurrentModule : ModuleName;
const CanAssumeFunctionDefs : bool;
const unique mu : Field (Mu);
const $LockBottom : Mu;
const unique held : Field (int);
const unique rdheld : Field (bool);
const ZeroCredits : CreditsType;
const unique AVLTree#t : TypeName;
const unique module#default : ModuleName;
const unique AVLTree.root : Field (ref);
const unique AVLTree.keys : Field (Seq (int));
const unique AVLTree.valid : Field (int);
const unique AVLTreeNode#t : TypeName;
const unique AVLTreeNode.key : Field (int);
const unique AVLTreeNode.height : Field (int);
const unique AVLTreeNode.left : Field (ref);
const unique AVLTreeNode.right : Field (ref);
const unique AVLTreeNode.keys : Field (Seq (int));
const unique AVLTreeNode.balanceFactor : Field (int);
const unique AVLTreeNode.valid : Field (int);
const $old_Heap : HeapType;
const $old_Mask : MaskType;
const $old_SecMask : MaskType;
const $old_Credits : CreditsType;
function Fractions(int) : int;
function IsGoodState(PartialHeapType) : bool;
function combine(PartialHeapType,PartialHeapType) : PartialHeapType;
function heapFragment <T> (T) : PartialHeapType;
function dtype(ref) : TypeName;
function MuBelow(Mu,Mu) : bool;
function Acquire$Heap(int) : HeapType;
function Acquire$Mask(int) : MaskType;
function Acquire$SecMask(int) : MaskType;
function Acquire$Credits(int) : CreditsType;
function LastSeen$Heap(Mu,int) : HeapType;
function LastSeen$Mask(Mu,int) : MaskType;
function LastSeen$SecMask(Mu,int) : MaskType;
function LastSeen$Credits(Mu,int) : CreditsType;
function wf(HeapType,MaskType,MaskType) : bool;
function IsGoodInhaleState(HeapType,HeapType,MaskType,MaskType) : bool;
function IsGoodExhaleState(HeapType,HeapType,MaskType,MaskType) : bool;
function CanRead <T> (MaskType,MaskType,ref,Field (T)) : bool;
function CanReadForSure <T> (MaskType,ref,Field (T)) : bool;
function CanWrite <T> (MaskType,ref,Field (T)) : bool;
function IsGoodMask(MaskType) : bool;
function DecPerm <T> (MaskType,ref,Field (T),int) : MaskType;
function DecEpsilons <T> (MaskType,ref,Field (T),int) : MaskType;
function IncPerm <T> (MaskType,ref,Field (T),int) : MaskType;
function IncEpsilons <T> (MaskType,ref,Field (T),int) : MaskType;
function Havocing <T,U> (HeapType,ref,Field (T),U) : HeapType;
function Call$Heap(int) : HeapType;
function Call$Mask(int) : MaskType;
function Call$SecMask(int) : MaskType;
function Call$Credits(int) : CreditsType;
function Call$Args(int) : ArgSeq;
function EmptyMask(MaskType) : bool;
function EmptyCredits(CreditsType) : bool;
function NonPredicateField <T> (Field (T)) : bool;
function PredicateField <T> (Field (T)) : bool;
function submask(MaskType,MaskType) : bool;
function ite <T> (bool,T,T) : T;
function Seq#Length <T> (Seq (T)) : int;
function Seq#Empty <T> () : Seq (T);
function Seq#Singleton <T> (T) : Seq (T);
function Seq#Build <T> (Seq (T),int,T,int) : Seq (T);
function Seq#Append <T> (Seq (T),Seq (T)) : Seq (T);
function Seq#Index <T> (Seq (T),int) : T;
function Seq#Contains <T> (Seq (T),T) : bool;
function Seq#Equal <T> (Seq (T),Seq (T)) : bool;
function Seq#SameUntil <T> (Seq (T),Seq (T),int) : bool;
function Seq#Take <T> (Seq (T),int) : Seq (T);
function Seq#Drop <T> (Seq (T),int) : Seq (T);
function Seq#Range(int,int) : Seq (int);
function #AVLTree.valid#trigger(ref) : bool;
function #AVLTreeNode.valid#trigger(ref) : bool;
var Heap : HeapType;
var Mask : MaskType;
var SecMask : MaskType;
var Credits : CreditsType;
var this#150 : ref;
var methodK#_224 : int;
var Mask_$_0 : MaskType;
var Mask_$_1 : MaskType;
var Mask_$_2 : MaskType;
var Mask_$_3 : MaskType;
var Mask_$_4 : MaskType;
var Mask_$_5 : MaskType;
var Heap_$_0 : HeapType;
var Heap_$_1 : HeapType;
var Heap_$_2 : HeapType;
var exhaleHeap#_229_$_0 : HeapType;
var methodCallK#_235 : int;
var exhaleMask#_237_$_0 : MaskType;
var exhaleMask#_237_$_1 : MaskType;
var exhaleMask#_237_$_2 : MaskType;
var exhaleMask#_237_$_3 : MaskType;
var exhaleMask#_237_$_4 : MaskType;
var exhaleMask#_237_$_5 : MaskType;
var exhaleMask#_237_$_7 : MaskType;
var exhaleMask#_237_$_9 : MaskType;
var exhaleMask#_237_$_11 : MaskType;
var exhaleMask#_237_$_13 : MaskType;
var exhaleMask#_237_$_15 : MaskType;
var exhaleMask#_237_$_17 : MaskType;
var exhaleMask#_237_$_19 : MaskType;
var exhaleMask#_237_$_21 : MaskType;
var exhaleHeap#_236_$_0 : HeapType;
var Mask_$_6 : MaskType;
var Mask_$_7 : MaskType;
var Mask_$_8 : MaskType;
var Mask_$_9 : MaskType;
var exhaleMask#_255_$_0 : MaskType;
var exhaleMask#_255_$_1 : MaskType;
var exhaleMask#_255_$_2 : MaskType;
var exhaleMask#_255_$_3 : MaskType;
var exhaleHeap#_254_$_0 : HeapType;
var exhaleMask#_237_$_20 : MaskType;
var exhaleMask#_237_$_18 : MaskType;
var exhaleMask#_237_$_16 : MaskType;
var exhaleMask#_237_$_14 : MaskType;
var exhaleMask#_237_$_12 : MaskType;
var exhaleMask#_237_$_10 : MaskType;
var exhaleMask#_237_$_8 : MaskType;
var exhaleMask#_237_$_6 : MaskType;
var assertHeap#_225 : HeapType;
var assertMask#_226 : MaskType;
var assertSecMask#_227 : MaskType;
var assertCredits#_228 : CreditsType;
var exhaleMask#_230 : MaskType;
var exhaleHeap#_229 : HeapType;
var callHeap#_231 : HeapType;
var callMask#_232 : MaskType;
var callSecMask#_233 : MaskType;
var callCredits#_234 : CreditsType;
var exhaleMask#_237 : MaskType;
var exhaleHeap#_236 : HeapType;
var exhaleMask#_255 : MaskType;
var exhaleHeap#_254 : HeapType;
procedure AVLTreeNode.init (this : ref,k#8 : int)
{
	var methodK#_224 : int;
	var assertHeap#_225 : HeapType;
	var assertMask#_226 : MaskType;
	var assertSecMask#_227 : MaskType;
	var assertCredits#_228 : CreditsType;
	var exhaleMask#_230 : MaskType;
	var exhaleHeap#_229 : HeapType;
	var methodCallK#_235 : int;
	var this#150 : ref;
	var callHeap#_231 : HeapType;
	var callMask#_232 : MaskType;
	var callSecMask#_233 : MaskType;
	var callCredits#_234 : CreditsType;
	var exhaleMask#_237 : MaskType;
	var exhaleHeap#_236 : HeapType;
	var exhaleMask#_255 : MaskType;
	var exhaleHeap#_254 : HeapType;
	var Mask_$_0 : MaskType;
	var Mask_$_1 : MaskType;
	var Mask_$_2 : MaskType;
	var Mask_$_3 : MaskType;
	var Mask_$_4 : MaskType;
	var Mask_$_5 : MaskType;
	var Heap_$_0 : HeapType;
	var Heap_$_1 : HeapType;
	var Heap_$_2 : HeapType;
	var exhaleHeap#_229_$_0 : HeapType;
	var exhaleHeap#_236_$_0 : HeapType;
	var exhaleMask#_237_$_0 : MaskType;
	var exhaleMask#_237_$_1 : MaskType;
	var exhaleMask#_237_$_2 : MaskType;
	var exhaleMask#_237_$_3 : MaskType;
	var exhaleMask#_237_$_4 : MaskType;
	var exhaleMask#_237_$_5 : MaskType;
	var exhaleMask#_237_$_6 : MaskType;
	var exhaleMask#_237_$_7 : MaskType;
	var exhaleMask#_237_$_8 : MaskType;
	var exhaleMask#_237_$_9 : MaskType;
	var exhaleMask#_237_$_10 : MaskType;
	var exhaleMask#_237_$_11 : MaskType;
	var exhaleMask#_237_$_12 : MaskType;
	var exhaleMask#_237_$_13 : MaskType;
	var exhaleMask#_237_$_14 : MaskType;
	var exhaleMask#_237_$_15 : MaskType;
	var exhaleMask#_237_$_16 : MaskType;
	var exhaleMask#_237_$_17 : MaskType;
	var exhaleMask#_237_$_18 : MaskType;
	var exhaleMask#_237_$_19 : MaskType;
	var exhaleMask#_237_$_20 : MaskType;
	var exhaleMask#_237_$_21 : MaskType;
	var Mask_$_6 : MaskType;
	var Mask_$_7 : MaskType;
	var Mask_$_8 : MaskType;
	var Mask_$_9 : MaskType;
	var exhaleHeap#_254_$_0 : HeapType;
	var exhaleMask#_255_$_0 : MaskType;
	var exhaleMask#_255_$_1 : MaskType;
	var exhaleMask#_255_$_2 : MaskType;
	var exhaleMask#_255_$_3 : MaskType;
	var $_$_condition : bool;
	var $_$_condition_$0 : bool;
	var $_$_condition_$1 : bool;
	var $_$_condition_$2 : bool;
	var $_$_condition_$3 : bool;
	var $_$_condition_$4 : bool;
	var $_$_condition_$5 : bool;
	var $_$_condition_$6 : bool;
	var $_$_condition_$7 : bool;
	var $_$_condition_$8 : bool;
	var $_$_condition_$9 : bool;
	var $_$_condition_$10 : bool;
	var $_$_condition_$11 : bool;
	var $_$_condition_$12 : bool;
	var $_$_condition_$13 : bool;
	var $_$_condition_$14 : bool;
	var $_$_condition_$15 : bool;
	var $_$_condition_$16 : bool;
	var $_$_condition_$17 : bool;
	var $_$_condition_$18 : bool;
	var $_$_condition_$19 : bool;
$start:
	assume Permission$denominator > 0;
	assume (Permission$Zero[perm$R] == 0) && (Permission$Zero[perm$N] == 0);
	assume (Permission$Full[perm$R] == Permission$FullFraction) && (Permission$Full[perm$N] == 0);
	assume (forall<T> o : ref, f : Field (T) , pc : PermissionComponent :: ( ZeroMask[o,f][pc] == 0 ));
	assume IsGoodMask(ZeroMask);
	assume NonPredicateField(joinable);
	assume NonPredicateField(forkK);
	assume (forall  n : Integer :: {Fractions(n)} ( Fractions(n) == (n * Permission$denominator) ));
	assume (forall  x : Integer, y : Integer :: ( ((0 <= x) && (x <= y)) ==> (Fractions(x) <= Fractions(y)) ));
	assume Permission$FullFraction == Fractions(100);
	assume (0 < channelK) && ((1000 * channelK) < Fractions(1));
	assume (0 < monitorK) && ((1000 * monitorK) < Fractions(1));
	assume (0 < predicateK) && ((1000 * predicateK) < Fractions(1));
	assume (predicateK == channelK) && (channelK == monitorK);
	assume (forall  a : PartialHeapType, b : PartialHeapType :: {IsGoodState(combine(a,b))} ( IsGoodState(combine(a,b)) <==> (IsGoodState(a) && IsGoodState(b)) ));
	assume IsGoodState(emptyPartialHeap);
	assume NonPredicateField(mu);
	assume (forall  m : Mu, n_$0 : Mu :: {MuBelow(m,n_$0),MuBelow(n_$0,m)} ( !(MuBelow(m,n_$0) && MuBelow(n_$0,m)) ));
	assume (forall  m_$0 : Mu, n_$1 : Mu, o_$0 : Mu :: {MuBelow(m_$0,n_$1),MuBelow(n_$1,o_$0)} ( (MuBelow(m_$0,n_$1) && MuBelow(n_$1,o_$0)) ==> MuBelow(m_$0,o_$0) ));
	assume (forall  m_$1 : Mu, n_$2 : Mu :: ( MuBelow(m_$1,n_$2) ==> (!(n_$2 == $LockBottom)) ));
	assume NonPredicateField(held);
	assume NonPredicateField(rdheld);
	assume (forall  ih : HeapType, h : HeapType, m_$2 : MaskType, sm : MaskType :: {IsGoodInhaleState(ih,h,m_$2,sm)} ( IsGoodInhaleState(ih,h,m_$2,sm) <==> ((((((forall<T> o_$1 : ref, f_$0 : Field (T)  :: {ih[o_$1,f_$0]} ( CanRead(m_$2,sm,o_$1,f_$0) ==> (ih[o_$1,f_$0] == h[o_$1,f_$0]) ))) && ((forall  o_$2 : ref :: {ih[o_$2,held]} ( (0 < ih[o_$2,held]) <==> (0 < h[o_$2,held]) )))) && ((forall  o_$3 : ref :: {ih[o_$3,rdheld]} ( ih[o_$3,rdheld] <==> h[o_$3,rdheld] )))) && ((forall  o_$4 : ref :: {h[o_$4,held]} ( (0 < h[o_$4,held]) ==> (ih[o_$4,mu] == h[o_$4,mu]) )))) && ((forall  o_$5 : ref :: {h[o_$5,rdheld]} ( h[o_$5,rdheld] ==> (ih[o_$5,mu] == h[o_$5,mu]) )))) ));
	assume (forall  eh : HeapType, h_$0 : HeapType, m_$3 : MaskType, sm_$0 : MaskType :: {IsGoodExhaleState(eh,h_$0,m_$3,sm_$0)} ( IsGoodExhaleState(eh,h_$0,m_$3,sm_$0) <==> (((((((((forall<T> o_$6 : ref, f_$1 : Field (T)  :: {eh[o_$6,f_$1]} ( CanRead(m_$3,sm_$0,o_$6,f_$1) ==> (eh[o_$6,f_$1] == h_$0[o_$6,f_$1]) ))) && ((forall  o_$7 : ref :: {eh[o_$7,held]} ( (0 < eh[o_$7,held]) <==> (0 < h_$0[o_$7,held]) )))) && ((forall  o_$8 : ref :: {eh[o_$8,rdheld]} ( eh[o_$8,rdheld] <==> h_$0[o_$8,rdheld] )))) && ((forall  o_$9 : ref :: {h_$0[o_$9,held]} ( (0 < h_$0[o_$9,held]) ==> (eh[o_$9,mu] == h_$0[o_$9,mu]) )))) && ((forall  o_$10 : ref :: {h_$0[o_$10,rdheld]} ( h_$0[o_$10,rdheld] ==> (eh[o_$10,mu] == h_$0[o_$10,mu]) )))) && ((forall  o_$11 : ref :: {h_$0[o_$11,forkK]} {eh[o_$11,forkK]} ( h_$0[o_$11,forkK] == eh[o_$11,forkK] )))) && ((forall  o_$12 : ref :: {h_$0[o_$12,held]} {eh[o_$12,held]} ( h_$0[o_$12,held] == eh[o_$12,held] )))) && ((forall  o_$13 : ref, f_$2 : Field (Integer)  :: {eh[o_$13,f_$2],PredicateField(f_$2)} ( PredicateField(f_$2) ==> (h_$0[o_$13,f_$2] <= eh[o_$13,f_$2]) )))) ));
	assume (forall<T> m_$4 : MaskType, sm_$1 : MaskType, obj : ref, f_$3 : Field (T)  :: {CanRead(m_$4,sm_$1,obj,f_$3)} ( CanRead(m_$4,sm_$1,obj,f_$3) <==> ((((0 < m_$4[obj,f_$3][perm$R]) || (0 < m_$4[obj,f_$3][perm$N])) || (0 < sm_$1[obj,f_$3][perm$R])) || (0 < sm_$1[obj,f_$3][perm$N])) ));
	assume (forall<T> m_$5 : MaskType, obj_$0 : ref, f_$4 : Field (T)  :: {CanReadForSure(m_$5,obj_$0,f_$4)} ( CanReadForSure(m_$5,obj_$0,f_$4) <==> ((0 < m_$5[obj_$0,f_$4][perm$R]) || (0 < m_$5[obj_$0,f_$4][perm$N])) ));
	assume (forall<T> m_$6 : MaskType, obj_$1 : ref, f_$5 : Field (T)  :: {CanWrite(m_$6,obj_$1,f_$5)} ( CanWrite(m_$6,obj_$1,f_$5) <==> ((m_$6[obj_$1,f_$5][perm$R] == Permission$FullFraction) && (m_$6[obj_$1,f_$5][perm$N] == 0)) ));
	assume (forall  m_$7 : MaskType :: {IsGoodMask(m_$7)} ( IsGoodMask(m_$7) <==> ((forall<T> o_$14 : ref, f_$6 : Field (T)  :: ( ((0 <= m_$7[o_$14,f_$6][perm$R]) && (NonPredicateField(f_$6) ==> ((m_$7[o_$14,f_$6][perm$R] <= Permission$FullFraction) && ((0 < m_$7[o_$14,f_$6][perm$N]) ==> (m_$7[o_$14,f_$6][perm$R] < Permission$FullFraction))))) && ((m_$7[o_$14,f_$6][perm$N] < 0) ==> (0 < m_$7[o_$14,f_$6][perm$R])) ))) ));
	assume (forall  h_$1 : HeapType, m_$8 : MaskType, sm_$2 : MaskType, o_$15 : ref, q : ref :: {wf(h_$1,m_$8,sm_$2),h_$1[o_$15,mu],h_$1[q,mu]} ( (((wf(h_$1,m_$8,sm_$2) && (!(o_$15 == q))) && ((0 < h_$1[o_$15,held]) || h_$1[o_$15,rdheld])) && ((0 < h_$1[q,held]) || h_$1[q,rdheld])) ==> (!(h_$1[o_$15,mu] == h_$1[q,mu])) ));
	assume (forall<T,U> m_$9 : MaskType, o_$16 : ref, f_$7 : Field (T) , howMuch : Integer, q_$0 : ref, g : Field (U)  :: {DecPerm(m_$9,o_$16,f_$7,howMuch)[q_$0,g][perm$R]} ( DecPerm(m_$9,o_$16,f_$7,howMuch)[q_$0,g][perm$R] == ite((o_$16 == q_$0) && (f_$7 == g),m_$9[q_$0,g][perm$R] - howMuch,m_$9[q_$0,g][perm$R]) ));
	assume (forall<T,U> m_$10 : MaskType, o_$17 : ref, f_$8 : Field (T) , howMuch_$0 : Integer, q_$1 : ref, g_$0 : Field (U)  :: {DecPerm(m_$10,o_$17,f_$8,howMuch_$0)[q_$1,g_$0][perm$N]} ( DecEpsilons(m_$10,o_$17,f_$8,howMuch_$0)[q_$1,g_$0][perm$N] == ite((o_$17 == q_$1) && (f_$8 == g_$0),m_$10[q_$1,g_$0][perm$N] - howMuch_$0,m_$10[q_$1,g_$0][perm$N]) ));
	assume (forall<T,U> m_$11 : MaskType, o_$18 : ref, f_$9 : Field (T) , howMuch_$1 : Integer, q_$2 : ref, g_$1 : Field (U)  :: {IncPerm(m_$11,o_$18,f_$9,howMuch_$1)[q_$2,g_$1][perm$R]} ( IncPerm(m_$11,o_$18,f_$9,howMuch_$1)[q_$2,g_$1][perm$R] == ite((o_$18 == q_$2) && (f_$9 == g_$1),m_$11[q_$2,g_$1][perm$R] + howMuch_$1,m_$11[q_$2,g_$1][perm$R]) ));
	assume (forall<T,U> m_$12 : MaskType, o_$19 : ref, f_$10 : Field (T) , howMuch_$2 : Integer, q_$3 : ref, g_$2 : Field (U)  :: {IncPerm(m_$12,o_$19,f_$10,howMuch_$2)[q_$3,g_$2][perm$N]} ( IncEpsilons(m_$12,o_$19,f_$10,howMuch_$2)[q_$3,g_$2][perm$N] == ite((o_$19 == q_$3) && (f_$10 == g_$2),m_$12[q_$3,g_$2][perm$N] + howMuch_$2,m_$12[q_$3,g_$2][perm$N]) ));
	assume (forall<T,U> h_$2 : HeapType, o_$20 : ref, f_$11 : Field (T) , newValue : U, q_$4 : ref, g_$3 : Field (U)  :: {Havocing(h_$2,o_$20,f_$11,newValue)[q_$4,g_$3]} ( Havocing(h_$2,o_$20,f_$11,newValue)[q_$4,g_$3] == ite((o_$20 == q_$4) && (f_$11 == g_$3),newValue,h_$2[q_$4,g_$3]) ));
	assume (forall  m_$13 : MaskType :: {EmptyMask(m_$13)} ( EmptyMask(m_$13) <==> ((forall<T> o_$21 : ref, f_$12 : Field (T)  :: ( NonPredicateField(f_$12) ==> ((m_$13[o_$21,f_$12][perm$R] <= 0) && (m_$13[o_$21,f_$12][perm$N] <= 0)) ))) ));
	assume (forall  o_$22 : ref :: ( ZeroCredits[o_$22] == 0 ));
	assume (forall  c : CreditsType :: {EmptyCredits(c)} ( EmptyCredits(c) <==> ((forall  o_$23 : ref :: ( (!(o_$23 == null)) ==> (c[o_$23] == 0) ))) ));
	assume (forall<T> f_$13 : Field (T)  :: ( NonPredicateField(f_$13) ==> (!PredicateField(f_$13)) ));
	assume (forall<T> f_$14 : Field (T)  :: ( PredicateField(f_$14) ==> (!NonPredicateField(f_$14)) ));
	assume (forall  m1 : MaskType, m2 : MaskType :: {submask(m1,m2)} ( submask(m1,m2) <==> ((forall<T> o_$24 : ref, f_$15 : Field (T)  :: ( (m1[o_$24,f_$15][perm$R] < m2[o_$24,f_$15][perm$R]) || ((m1[o_$24,f_$15][perm$R] == m2[o_$24,f_$15][perm$R]) && (m1[o_$24,f_$15][perm$N] <= m2[o_$24,f_$15][perm$N])) ))) ));
	assume (forall<T> con : Boolean, a_$0 : T, b_$0 : T :: {ite(con,a_$0,b_$0)} ( con ==> (ite(con,a_$0,b_$0) == a_$0) ));
	assume (forall<T> con_$0 : Boolean, a_$1 : T, b_$1 : T :: {ite(con_$0,a_$1,b_$1)} ( (!con_$0) ==> (ite(con_$0,a_$1,b_$1) == b_$1) ));
	assume (forall<T> s : Seq (T)  :: {Seq#Length(s)} ( 0 <= Seq#Length(s) ));
	assume (forall<T> :: Seq#Length((Seq#Empty() : Seq (T) )) == 0);
	assume (forall<T> s_$0 : Seq (T)  :: {Seq#Length(s_$0)} ( (Seq#Length(s_$0) == 0) ==> (s_$0 == (Seq#Empty() : Seq (T) )) ));
	assume (forall<T> t : T :: {Seq#Length(Seq#Singleton(t))} ( Seq#Length(Seq#Singleton(t)) == 1 ));
	assume (forall<T> s_$1 : Seq (T) , i : Integer, v : T, len : Integer :: {Seq#Length(Seq#Build(s_$1,i,v,len))} ( (0 <= len) ==> (Seq#Length(Seq#Build(s_$1,i,v,len)) == len) ));
	assume (forall<T> s0 : Seq (T) , s1 : Seq (T)  :: {Seq#Length(Seq#Append(s0,s1))} ( Seq#Length(Seq#Append(s0,s1)) == (Seq#Length(s0) + Seq#Length(s1)) ));
	assume (forall<T> t_$0 : T :: {Seq#Index(Seq#Singleton(t_$0),0)} ( Seq#Index(Seq#Singleton(t_$0),0) == t_$0 ));
	assume (forall<T> s0_$0 : Seq (T) , s1_$0 : Seq (T) , n_$3 : Integer :: {Seq#Index(Seq#Append(s0_$0,s1_$0),n_$3)} ( ((n_$3 < Seq#Length(s0_$0)) ==> (Seq#Index(Seq#Append(s0_$0,s1_$0),n_$3) == Seq#Index(s0_$0,n_$3))) && ((Seq#Length(s0_$0) <= n_$3) ==> (Seq#Index(Seq#Append(s0_$0,s1_$0),n_$3) == Seq#Index(s1_$0,n_$3 - Seq#Length(s0_$0)))) ));
	assume (forall<T> s_$2 : Seq (T) , i_$0 : Integer, v_$0 : T, len_$0 : Integer, n_$4 : Integer :: {Seq#Index(Seq#Build(s_$2,i_$0,v_$0,len_$0),n_$4)} ( ((0 <= n_$4) && (n_$4 < len_$0)) ==> (((i_$0 == n_$4) ==> (Seq#Index(Seq#Build(s_$2,i_$0,v_$0,len_$0),n_$4) == v_$0)) && ((!(i_$0 == n_$4)) ==> (Seq#Index(Seq#Build(s_$2,i_$0,v_$0,len_$0),n_$4) == Seq#Index(s_$2,n_$4)))) ));
	assume (forall<T> s_$3 : Seq (T) , x_$0 : T :: {Seq#Contains(s_$3,x_$0)} ( Seq#Contains(s_$3,x_$0) <==> ((exists  i_$1 : Integer :: {Seq#Index(s_$3,i_$1)} ( ((0 <= i_$1) && (i_$1 < Seq#Length(s_$3))) && (Seq#Index(s_$3,i_$1) == x_$0) ))) ));
	assume (forall  x_$1 : ref :: {Seq#Contains((Seq#Empty() : Seq (ref) ),x_$1)} ( !Seq#Contains((Seq#Empty() : Seq (ref) ),x_$1) ));
	assume (forall<T> s0_$1 : Seq (T) , s1_$1 : Seq (T) , x_$2 : T :: {Seq#Contains(Seq#Append(s0_$1,s1_$1),x_$2)} ( Seq#Contains(Seq#Append(s0_$1,s1_$1),x_$2) <==> (Seq#Contains(s0_$1,x_$2) || Seq#Contains(s1_$1,x_$2)) ));
	assume (forall<T> s_$4 : Seq (T) , i_$2 : Integer, v_$1 : T, len_$1 : Integer, x_$3 : T :: {Seq#Contains(Seq#Build(s_$4,i_$2,v_$1,len_$1),x_$3)} ( Seq#Contains(Seq#Build(s_$4,i_$2,v_$1,len_$1),x_$3) <==> ((((0 <= i_$2) && (i_$2 < len_$1)) && (x_$3 == v_$1)) || ((exists  j : Integer :: {Seq#Index(s_$4,j)} ( ((((0 <= j) && (j < Seq#Length(s_$4))) && (j < len_$1)) && (!(j == i_$2))) && (Seq#Index(s_$4,j) == x_$3) )))) ));
	assume (forall<T> s_$5 : Seq (T) , n_$5 : Integer, x_$4 : T :: {Seq#Contains(Seq#Take(s_$5,n_$5),x_$4)} ( Seq#Contains(Seq#Take(s_$5,n_$5),x_$4) <==> ((exists  i_$3 : Integer :: {Seq#Index(s_$5,i_$3)} ( (((0 <= i_$3) && (i_$3 < n_$5)) && (i_$3 < Seq#Length(s_$5))) && (Seq#Index(s_$5,i_$3) == x_$4) ))) ));
	assume (forall<T> s_$6 : Seq (T) , n_$6 : Integer, x_$5 : T :: {Seq#Contains(Seq#Drop(s_$6,n_$6),x_$5)} ( Seq#Contains(Seq#Drop(s_$6,n_$6),x_$5) <==> ((exists  i_$4 : Integer :: {Seq#Index(s_$6,i_$4)} ( (((0 <= n_$6) && (n_$6 <= i_$4)) && (i_$4 < Seq#Length(s_$6))) && (Seq#Index(s_$6,i_$4) == x_$5) ))) ));
	assume (forall<T> s0_$2 : Seq (T) , s1_$2 : Seq (T)  :: {Seq#Equal(s0_$2,s1_$2)} ( Seq#Equal(s0_$2,s1_$2) <==> ((Seq#Length(s0_$2) == Seq#Length(s1_$2)) && ((forall  j_$0 : Integer :: {Seq#Index(s0_$2,j_$0)} {Seq#Index(s1_$2,j_$0)} ( ((0 <= j_$0) && (j_$0 < Seq#Length(s0_$2))) ==> (Seq#Index(s0_$2,j_$0) == Seq#Index(s1_$2,j_$0)) )))) ));
	assume (forall<T> a_$2 : Seq (T) , b_$2 : Seq (T)  :: {Seq#Equal(a_$2,b_$2)} ( Seq#Equal(a_$2,b_$2) ==> (a_$2 == b_$2) ));
	assume (forall<T> s0_$3 : Seq (T) , s1_$3 : Seq (T) , n_$7 : Integer :: {Seq#SameUntil(s0_$3,s1_$3,n_$7)} ( Seq#SameUntil(s0_$3,s1_$3,n_$7) <==> ((forall  j_$1 : Integer :: {Seq#Index(s0_$3,j_$1)} {Seq#Index(s1_$3,j_$1)} ( ((0 <= j_$1) && (j_$1 < n_$7)) ==> (Seq#Index(s0_$3,j_$1) == Seq#Index(s1_$3,j_$1)) ))) ));
	assume (forall<T> s_$7 : Seq (T) , n_$8 : Integer :: {Seq#Length(Seq#Take(s_$7,n_$8))} ( (0 <= n_$8) ==> (((n_$8 <= Seq#Length(s_$7)) ==> (Seq#Length(Seq#Take(s_$7,n_$8)) == n_$8)) && ((Seq#Length(s_$7) < n_$8) ==> (Seq#Length(Seq#Take(s_$7,n_$8)) == Seq#Length(s_$7)))) ));
	assume (forall<T> s_$8 : Seq (T) , n_$9 : Integer, j_$2 : Integer :: {Seq#Index(Seq#Take(s_$8,n_$9),j_$2)} {:weight  25}( (((0 <= j_$2) && (j_$2 < n_$9)) && (j_$2 < Seq#Length(s_$8))) ==> (Seq#Index(Seq#Take(s_$8,n_$9),j_$2) == Seq#Index(s_$8,j_$2)) ));
	assume (forall<T> s_$9 : Seq (T) , n_$10 : Integer :: {Seq#Length(Seq#Drop(s_$9,n_$10))} ( (0 <= n_$10) ==> (((n_$10 <= Seq#Length(s_$9)) ==> (Seq#Length(Seq#Drop(s_$9,n_$10)) == (Seq#Length(s_$9) - n_$10))) && ((Seq#Length(s_$9) < n_$10) ==> (Seq#Length(Seq#Drop(s_$9,n_$10)) == 0))) ));
	assume (forall<T> s_$10 : Seq (T) , n_$11 : Integer, j_$3 : Integer :: {Seq#Index(Seq#Drop(s_$10,n_$11),j_$3)} {:weight  25}( (((0 <= n_$11) && (0 <= j_$3)) && (j_$3 < (Seq#Length(s_$10) - n_$11))) ==> (Seq#Index(Seq#Drop(s_$10,n_$11),j_$3) == Seq#Index(s_$10,j_$3 + n_$11)) ));
	assume (forall<T> s_$11 : Seq (T) , t_$1 : Seq (T)  :: {Seq#Append(s_$11,t_$1)} ( (Seq#Take(Seq#Append(s_$11,t_$1),Seq#Length(s_$11)) == s_$11) && (Seq#Drop(Seq#Append(s_$11,t_$1),Seq#Length(s_$11)) == t_$1) ));
	assume (forall  min : Integer, max : Integer :: {Seq#Length(Seq#Range(min,max))} ( ((min < max) ==> (Seq#Length(Seq#Range(min,max)) == (max - min))) && ((max <= min) ==> (Seq#Length(Seq#Range(min,max)) == 0)) ));
	assume (forall  min_$0 : Integer, max_$0 : Integer, j_$4 : Integer :: {Seq#Index(Seq#Range(min_$0,max_$0),j_$4)} ( ((0 <= j_$4) && (j_$4 < (max_$0 - min_$0))) ==> (Seq#Index(Seq#Range(min_$0,max_$0),j_$4) == (min_$0 + j_$4)) ));
	assume (forall<T> x_$6 : T, y_$0 : T :: {Seq#Contains(Seq#Singleton(x_$6),y_$0)} ( Seq#Contains(Seq#Singleton(x_$6),y_$0) <==> (x_$6 == y_$0) ));
	assume NonPredicateField(AVLTree.root);
	assume NonPredicateField(AVLTree.keys);
	assume PredicateField(AVLTree.valid);
	assume NonPredicateField(AVLTreeNode.key);
	assume NonPredicateField(AVLTreeNode.height);
	assume NonPredicateField(AVLTreeNode.left);
	assume NonPredicateField(AVLTreeNode.right);
	assume NonPredicateField(AVLTreeNode.keys);
	assume NonPredicateField(AVLTreeNode.balanceFactor);
	assume PredicateField(AVLTreeNode.valid);
	goto PreconditionGeneratedEntry;
$exit:
	assume false;
PreconditionGeneratedEntry:
	assume IsGoodMask(Mask);
	assume IsGoodMask(SecMask);
	assume (this == null) || (dtype(this) == AVLTreeNode#t);
	assume true;
	assume (this#150 == null) || (dtype(this#150) == AVLTreeNode#t);
	assume !(this == null);
	assume wf(Heap,Mask,SecMask);
	goto anon0;
anon0:
	assume (0 < methodK#_224) && ((1000 * methodK#_224) < Fractions(1));
	assume CurrentModule == module#default;
	assume CanAssumeFunctionDefs;
	assume !(this == null);
	assume wf(Heap,ZeroMask,ZeroMask);
	assume true;
	assume Fractions(100) > 0;
	assume Mask_$_0 == ZeroMask[this,AVLTreeNode.key := ZeroMask[this,AVLTreeNode.key][perm$R := ZeroMask[this,AVLTreeNode.key][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_0);
	assume IsGoodState(heapFragment(Heap[this,AVLTreeNode.key]));
	assume wf(Heap,Mask_$_0,ZeroMask);
	assume wf(Heap,Mask_$_0,ZeroMask);
	assume !(this == null);
	assume wf(Heap,Mask_$_0,ZeroMask);
	assume true;
	assume Fractions(100) > 0;
	assume Mask_$_1 == Mask_$_0[this,AVLTreeNode.height := Mask_$_0[this,AVLTreeNode.height][perm$R := Mask_$_0[this,AVLTreeNode.height][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_1);
	assume IsGoodState(heapFragment(Heap[this,AVLTreeNode.height]));
	assume wf(Heap,Mask_$_1,ZeroMask);
	assume wf(Heap,Mask_$_1,ZeroMask);
	assume !(this == null);
	assume wf(Heap,Mask_$_1,ZeroMask);
	assume (Heap[this,AVLTreeNode.left] == null) || (dtype(Heap[this,AVLTreeNode.left]) == AVLTreeNode#t);
	assume Fractions(100) > 0;
	assume Mask_$_2 == Mask_$_1[this,AVLTreeNode.left := Mask_$_1[this,AVLTreeNode.left][perm$R := Mask_$_1[this,AVLTreeNode.left][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_2);
	assume IsGoodState(heapFragment(Heap[this,AVLTreeNode.left]));
	assume wf(Heap,Mask_$_2,ZeroMask);
	assume wf(Heap,Mask_$_2,ZeroMask);
	assume !(this == null);
	assume wf(Heap,Mask_$_2,ZeroMask);
	assume (Heap[this,AVLTreeNode.right] == null) || (dtype(Heap[this,AVLTreeNode.right]) == AVLTreeNode#t);
	assume Fractions(100) > 0;
	assume Mask_$_3 == Mask_$_2[this,AVLTreeNode.right := Mask_$_2[this,AVLTreeNode.right][perm$R := Mask_$_2[this,AVLTreeNode.right][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_3);
	assume IsGoodState(heapFragment(Heap[this,AVLTreeNode.right]));
	assume wf(Heap,Mask_$_3,ZeroMask);
	assume wf(Heap,Mask_$_3,ZeroMask);
	assume !(this == null);
	assume wf(Heap,Mask_$_3,ZeroMask);
	assume true;
	assume Fractions(100) > 0;
	assume Mask_$_4 == Mask_$_3[this,AVLTreeNode.keys := Mask_$_3[this,AVLTreeNode.keys][perm$R := Mask_$_3[this,AVLTreeNode.keys][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_4);
	assume IsGoodState(heapFragment(Heap[this,AVLTreeNode.keys]));
	assume wf(Heap,Mask_$_4,ZeroMask);
	assume wf(Heap,Mask_$_4,ZeroMask);
	assume !(this == null);
	assume wf(Heap,Mask_$_4,ZeroMask);
	assume true;
	assume Fractions(100) > 0;
	assume Mask_$_5 == Mask_$_4[this,AVLTreeNode.balanceFactor := Mask_$_4[this,AVLTreeNode.balanceFactor][perm$R := Mask_$_4[this,AVLTreeNode.balanceFactor][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_5);
	assume IsGoodState(heapFragment(Heap[this,AVLTreeNode.balanceFactor]));
	assume wf(Heap,Mask_$_5,ZeroMask);
	assume wf(Heap,Mask_$_5,ZeroMask);
	assume IsGoodMask(Mask_$_5);
	assume wf(Heap,Mask_$_5,ZeroMask);
	assume Heap == Heap;
	assume Mask_$_5 == Mask;
	assume ZeroMask == SecMask;
	assume ZeroCredits == Credits;
	assert { :msg "  174.3: Location might not be writable" } CanWrite(Mask_$_5,this,AVLTreeNode.left);
	assume Heap_$_0 == Heap[this,AVLTreeNode.left := null];
	assume wf(Heap_$_0,Mask_$_5,ZeroMask);
	assert { :msg "  175.3: Location might not be writable" } CanWrite(Mask_$_5,this,AVLTreeNode.right);
	assume Heap_$_1 == Heap_$_0[this,AVLTreeNode.right := null];
	assume wf(Heap_$_1,Mask_$_5,ZeroMask);
	assert { :msg "  176.3: Location might not be writable" } CanWrite(Mask_$_5,this,AVLTreeNode.key);
	assume Heap_$_2 == Heap_$_1[this,AVLTreeNode.key := k#8];
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assert { :msg "  178.10: Sequence index might be negative." } true ==> (0 <= 0);
	assert { :msg "  178.10: Sequence index might be larger than or equal to the length of the sequence." } true ==> (0 < Seq#Length(Seq#Singleton(k#8)));
	assert { :msg "  178.3: Assertion might not hold. The expression at 178.10 might not evaluate to true." } Seq#Index(Seq#Singleton(k#8),0) == k#8;
	assume IsGoodExhaleState(exhaleHeap#_229_$_0,Heap_$_2,Mask_$_5,ZeroMask);
	assume IsGoodMask(Mask_$_5);
	assume wf(exhaleHeap#_229_$_0,Mask_$_5,ZeroMask);
	assume ((0 < methodCallK#_235) && ((1000 * methodCallK#_235) < Fractions(1))) && ((1000 * methodCallK#_235) < methodK#_224);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assert { :msg "  179.3: The target of the method call might be null." } !(this == null);
	if ($_$_condition) { goto anon27_Then; } else { goto anon27_Else; }
anon27_Then:
	assume !(Heap_$_2[this,AVLTreeNode.left] == null);
	assert { :msg "  179.3: The precondition at 556.12 might not hold. The expression at 556.27 might not evaluate to true." } (forall  k#92#151 : Integer :: ( ((0 <= k#92#151) && (k#92#151 < Seq#Length(Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys]))) ==> (Seq#Index(Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys],k#92#151) < Heap_$_2[this,AVLTreeNode.key]) ));
	if ($_$_condition_$0) { goto anon28_Then; } else { goto anon28_Else; }
anon27_Else:
	assume Heap_$_2[this,AVLTreeNode.left] == null;
	if ($_$_condition_$1) { goto anon28_Then; } else { goto anon28_Else; }
anon28_Then:
	assume !(Heap_$_2[this,AVLTreeNode.right] == null);
	assert { :msg "  179.3: The precondition at 562.12 might not hold. The expression at 562.28 might not evaluate to true." } (forall  k#93#152 : Integer :: ( ((0 <= k#93#152) && (k#93#152 < Seq#Length(Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys]))) ==> (Heap_$_2[this,AVLTreeNode.key] < Seq#Index(Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys],k#93#152)) ));
	goto anon4;
anon28_Else:
	assume Heap_$_2[this,AVLTreeNode.right] == null;
	goto anon4;
anon4:
	assert { :msg "  179.3: The precondition at 564.12 might not hold. The expression at 564.12 might not evaluate to true." } (ite(Heap_$_2[this,AVLTreeNode.left] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height]) - ite(Heap_$_2[this,AVLTreeNode.right] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height])) <= 1;
	assert { :msg "  179.3: The precondition at 565.12 might not hold. The expression at 565.12 might not evaluate to true." } (ite(Heap_$_2[this,AVLTreeNode.left] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height]) - ite(Heap_$_2[this,AVLTreeNode.right] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height])) >= (0 - 1);
	assert { :msg "  179.3: The precondition at 544.12 might not hold. The permission at 544.12 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 544.12 might not hold. Insufficient fraction at 544.12 for AVLTreeNode.key." } (Fractions(100) <= Mask_$_5[this,AVLTreeNode.key][perm$R]) && ((Fractions(100) == Mask_$_5[this,AVLTreeNode.key][perm$R]) ==> (0 <= Mask_$_5[this,AVLTreeNode.key][perm$N]));
	assume exhaleMask#_237_$_0 == Mask_$_5[this,AVLTreeNode.key := Mask_$_5[this,AVLTreeNode.key][perm$R := Mask_$_5[this,AVLTreeNode.key][perm$R] - Fractions(100)]];
	assume IsGoodMask(exhaleMask#_237_$_0);
	assume wf(Heap_$_2,exhaleMask#_237_$_0,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assert { :msg "  179.3: The precondition at 545.12 might not hold. The permission at 545.12 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 545.12 might not hold. Insufficient fraction at 545.12 for AVLTreeNode.height." } (Fractions(100) <= exhaleMask#_237_$_0[this,AVLTreeNode.height][perm$R]) && ((Fractions(100) == exhaleMask#_237_$_0[this,AVLTreeNode.height][perm$R]) ==> (0 <= exhaleMask#_237_$_0[this,AVLTreeNode.height][perm$N]));
	assume exhaleMask#_237_$_1 == exhaleMask#_237_$_0[this,AVLTreeNode.height := exhaleMask#_237_$_0[this,AVLTreeNode.height][perm$R := exhaleMask#_237_$_0[this,AVLTreeNode.height][perm$R] - Fractions(100)]];
	assume IsGoodMask(exhaleMask#_237_$_1);
	assume wf(Heap_$_2,exhaleMask#_237_$_1,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assert { :msg "  179.3: The precondition at 546.12 might not hold. The permission at 546.12 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 546.12 might not hold. Insufficient fraction at 546.12 for AVLTreeNode.left." } (Fractions(100) <= exhaleMask#_237_$_1[this,AVLTreeNode.left][perm$R]) && ((Fractions(100) == exhaleMask#_237_$_1[this,AVLTreeNode.left][perm$R]) ==> (0 <= exhaleMask#_237_$_1[this,AVLTreeNode.left][perm$N]));
	assume exhaleMask#_237_$_2 == exhaleMask#_237_$_1[this,AVLTreeNode.left := exhaleMask#_237_$_1[this,AVLTreeNode.left][perm$R := exhaleMask#_237_$_1[this,AVLTreeNode.left][perm$R] - Fractions(100)]];
	assume IsGoodMask(exhaleMask#_237_$_2);
	assume wf(Heap_$_2,exhaleMask#_237_$_2,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assert { :msg "  179.3: The precondition at 547.12 might not hold. The permission at 547.12 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 547.12 might not hold. Insufficient fraction at 547.12 for AVLTreeNode.right." } (Fractions(100) <= exhaleMask#_237_$_2[this,AVLTreeNode.right][perm$R]) && ((Fractions(100) == exhaleMask#_237_$_2[this,AVLTreeNode.right][perm$R]) ==> (0 <= exhaleMask#_237_$_2[this,AVLTreeNode.right][perm$N]));
	assume exhaleMask#_237_$_3 == exhaleMask#_237_$_2[this,AVLTreeNode.right := exhaleMask#_237_$_2[this,AVLTreeNode.right][perm$R := exhaleMask#_237_$_2[this,AVLTreeNode.right][perm$R] - Fractions(100)]];
	assume IsGoodMask(exhaleMask#_237_$_3);
	assume wf(Heap_$_2,exhaleMask#_237_$_3,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assert { :msg "  179.3: The precondition at 549.12 might not hold. The permission at 549.12 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 549.12 might not hold. Insufficient fraction at 549.12 for AVLTreeNode.keys." } (Fractions(100) <= exhaleMask#_237_$_3[this,AVLTreeNode.keys][perm$R]) && ((Fractions(100) == exhaleMask#_237_$_3[this,AVLTreeNode.keys][perm$R]) ==> (0 <= exhaleMask#_237_$_3[this,AVLTreeNode.keys][perm$N]));
	assume exhaleMask#_237_$_4 == exhaleMask#_237_$_3[this,AVLTreeNode.keys := exhaleMask#_237_$_3[this,AVLTreeNode.keys][perm$R := exhaleMask#_237_$_3[this,AVLTreeNode.keys][perm$R] - Fractions(100)]];
	assume IsGoodMask(exhaleMask#_237_$_4);
	assume wf(Heap_$_2,exhaleMask#_237_$_4,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assert { :msg "  179.3: The precondition at 550.12 might not hold. The permission at 550.12 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 550.12 might not hold. Insufficient fraction at 550.12 for AVLTreeNode.balanceFactor." } (Fractions(100) <= exhaleMask#_237_$_4[this,AVLTreeNode.balanceFactor][perm$R]) && ((Fractions(100) == exhaleMask#_237_$_4[this,AVLTreeNode.balanceFactor][perm$R]) ==> (0 <= exhaleMask#_237_$_4[this,AVLTreeNode.balanceFactor][perm$N]));
	assume exhaleMask#_237_$_5 == exhaleMask#_237_$_4[this,AVLTreeNode.balanceFactor := exhaleMask#_237_$_4[this,AVLTreeNode.balanceFactor][perm$R := exhaleMask#_237_$_4[this,AVLTreeNode.balanceFactor][perm$R] - Fractions(100)]];
	assume IsGoodMask(exhaleMask#_237_$_5);
	assume wf(Heap_$_2,exhaleMask#_237_$_5,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	if ($_$_condition_$2) { goto anon29_Then; } else { goto anon29_Else; }
anon29_Then:
	assume !(Heap_$_2[this,AVLTreeNode.left] == null);
	assert { :msg "  179.3: The precondition at 552.12 might not hold. The permission at 552.27 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 552.12 might not hold. Insufficient fraction at 552.27 for AVLTreeNode.valid." } (Fractions(100) <= exhaleMask#_237_$_5[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid][perm$R]) && ((Fractions(100) == exhaleMask#_237_$_5[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid][perm$R]) ==> (0 <= exhaleMask#_237_$_5[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid][perm$N]));
	assume exhaleMask#_237_$_6 == exhaleMask#_237_$_5[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid := exhaleMask#_237_$_5[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid][perm$R := exhaleMask#_237_$_5[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid][perm$R] - Fractions(100)]];
	if ($_$_condition_$3) { goto anon30_Then; } else { goto anon30_Else; }
anon29_Else:
	assume Heap_$_2[this,AVLTreeNode.left] == null;
	assume exhaleMask#_237_$_7 == exhaleMask#_237_$_5;
	if ($_$_condition_$4) { goto anon31_Then; } else { goto anon31_Else; }
anon30_Then:
	assume !CanRead(exhaleMask#_237_$_6,ZeroMask,Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid);
	assume Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid] < exhaleHeap#_236_$_0[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid];
	goto anon7;
anon30_Else:
	assume CanRead(exhaleMask#_237_$_6,ZeroMask,Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.valid);
	goto anon7;
anon31_Then:
	assume !(Heap_$_2[this,AVLTreeNode.left] == null);
	assert { :msg "  179.3: The precondition at 553.12 might not hold. The permission at 553.27 might not be positive." } Fractions(50) > 0;
	assert { :msg "  179.3: The precondition at 553.12 might not hold. Insufficient fraction at 553.27 for AVLTreeNode.height." } (Fractions(50) <= exhaleMask#_237_$_7[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height][perm$R]) && ((Fractions(50) == exhaleMask#_237_$_7[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height][perm$R]) ==> (0 <= exhaleMask#_237_$_7[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height][perm$N]));
	assume exhaleMask#_237_$_8 == exhaleMask#_237_$_7[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height := exhaleMask#_237_$_7[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height][perm$R := exhaleMask#_237_$_7[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_237_$_8);
	assume wf(Heap_$_2,exhaleMask#_237_$_8,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_9 == exhaleMask#_237_$_8;
	if ($_$_condition_$6) { goto anon32_Then; } else { goto anon32_Else; }
anon31_Else:
	assume Heap_$_2[this,AVLTreeNode.left] == null;
	assume exhaleMask#_237_$_9 == exhaleMask#_237_$_7;
	if ($_$_condition_$7) { goto anon32_Then; } else { goto anon32_Else; }
anon7:
	assume IsGoodMask(exhaleMask#_237_$_6);
	assume wf(Heap_$_2,exhaleMask#_237_$_6,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_7 == exhaleMask#_237_$_6;
	if ($_$_condition_$5) { goto anon31_Then; } else { goto anon31_Else; }
anon32_Then:
	assume !(Heap_$_2[this,AVLTreeNode.left] == null);
	assert { :msg "  179.3: The precondition at 554.12 might not hold. The permission at 554.27 might not be positive." } Fractions(50) > 0;
	assert { :msg "  179.3: The precondition at 554.12 might not hold. Insufficient fraction at 554.27 for AVLTreeNode.keys." } (Fractions(50) <= exhaleMask#_237_$_9[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys][perm$R]) && ((Fractions(50) == exhaleMask#_237_$_9[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys][perm$R]) ==> (0 <= exhaleMask#_237_$_9[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys][perm$N]));
	assume exhaleMask#_237_$_10 == exhaleMask#_237_$_9[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys := exhaleMask#_237_$_9[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys][perm$R := exhaleMask#_237_$_9[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_237_$_10);
	assume wf(Heap_$_2,exhaleMask#_237_$_10,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_11 == exhaleMask#_237_$_10;
	if ($_$_condition_$8) { goto anon33_Then; } else { goto anon33_Else; }
anon32_Else:
	assume Heap_$_2[this,AVLTreeNode.left] == null;
	assume exhaleMask#_237_$_11 == exhaleMask#_237_$_9;
	if ($_$_condition_$9) { goto anon33_Then; } else { goto anon33_Else; }
anon33_Then:
	assume !(Heap_$_2[this,AVLTreeNode.left] == null);
	assert { :msg "  179.3: The precondition at 555.12 might not hold. The permission at 555.27 might not be positive." } Fractions(50) > 0;
	assert { :msg "  179.3: The precondition at 555.12 might not hold. Insufficient fraction at 555.27 for AVLTreeNode.balanceFactor." } (Fractions(50) <= exhaleMask#_237_$_11[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.balanceFactor][perm$R]) && ((Fractions(50) == exhaleMask#_237_$_11[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.balanceFactor][perm$R]) ==> (0 <= exhaleMask#_237_$_11[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.balanceFactor][perm$N]));
	assume exhaleMask#_237_$_12 == exhaleMask#_237_$_11[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.balanceFactor := exhaleMask#_237_$_11[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.balanceFactor][perm$R := exhaleMask#_237_$_11[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.balanceFactor][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_237_$_12);
	assume wf(Heap_$_2,exhaleMask#_237_$_12,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_13 == exhaleMask#_237_$_12;
	if ($_$_condition_$10) { goto anon34_Then; } else { goto anon34_Else; }
anon33_Else:
	assume Heap_$_2[this,AVLTreeNode.left] == null;
	assume exhaleMask#_237_$_13 == exhaleMask#_237_$_11;
	if ($_$_condition_$11) { goto anon34_Then; } else { goto anon34_Else; }
anon34_Then:
	assume !(Heap_$_2[this,AVLTreeNode.right] == null);
	assert { :msg "  179.3: The precondition at 558.12 might not hold. The permission at 558.28 might not be positive." } Fractions(100) > 0;
	assert { :msg "  179.3: The precondition at 558.12 might not hold. Insufficient fraction at 558.28 for AVLTreeNode.valid." } (Fractions(100) <= exhaleMask#_237_$_13[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid][perm$R]) && ((Fractions(100) == exhaleMask#_237_$_13[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid][perm$R]) ==> (0 <= exhaleMask#_237_$_13[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid][perm$N]));
	assume exhaleMask#_237_$_14 == exhaleMask#_237_$_13[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid := exhaleMask#_237_$_13[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid][perm$R := exhaleMask#_237_$_13[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid][perm$R] - Fractions(100)]];
	if ($_$_condition_$12) { goto anon35_Then; } else { goto anon35_Else; }
anon34_Else:
	assume Heap_$_2[this,AVLTreeNode.right] == null;
	assume exhaleMask#_237_$_15 == exhaleMask#_237_$_13;
	if ($_$_condition_$13) { goto anon36_Then; } else { goto anon36_Else; }
anon35_Then:
	assume !CanRead(exhaleMask#_237_$_14,ZeroMask,Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid);
	assume Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid] < exhaleHeap#_236_$_0[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid];
	goto anon17;
anon35_Else:
	assume CanRead(exhaleMask#_237_$_14,ZeroMask,Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.valid);
	goto anon17;
anon36_Then:
	assume !(Heap_$_2[this,AVLTreeNode.right] == null);
	assert { :msg "  179.3: The precondition at 559.12 might not hold. The permission at 559.28 might not be positive." } Fractions(50) > 0;
	assert { :msg "  179.3: The precondition at 559.12 might not hold. Insufficient fraction at 559.28 for AVLTreeNode.height." } (Fractions(50) <= exhaleMask#_237_$_15[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height][perm$R]) && ((Fractions(50) == exhaleMask#_237_$_15[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height][perm$R]) ==> (0 <= exhaleMask#_237_$_15[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height][perm$N]));
	assume exhaleMask#_237_$_16 == exhaleMask#_237_$_15[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height := exhaleMask#_237_$_15[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height][perm$R := exhaleMask#_237_$_15[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_237_$_16);
	assume wf(Heap_$_2,exhaleMask#_237_$_16,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_17 == exhaleMask#_237_$_16;
	if ($_$_condition_$15) { goto anon37_Then; } else { goto anon37_Else; }
anon36_Else:
	assume Heap_$_2[this,AVLTreeNode.right] == null;
	assume exhaleMask#_237_$_17 == exhaleMask#_237_$_15;
	if ($_$_condition_$16) { goto anon37_Then; } else { goto anon37_Else; }
anon17:
	assume IsGoodMask(exhaleMask#_237_$_14);
	assume wf(Heap_$_2,exhaleMask#_237_$_14,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_15 == exhaleMask#_237_$_14;
	if ($_$_condition_$14) { goto anon36_Then; } else { goto anon36_Else; }
anon37_Then:
	assume !(Heap_$_2[this,AVLTreeNode.right] == null);
	assert { :msg "  179.3: The precondition at 560.12 might not hold. The permission at 560.28 might not be positive." } Fractions(50) > 0;
	assert { :msg "  179.3: The precondition at 560.12 might not hold. Insufficient fraction at 560.28 for AVLTreeNode.keys." } (Fractions(50) <= exhaleMask#_237_$_17[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys][perm$R]) && ((Fractions(50) == exhaleMask#_237_$_17[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys][perm$R]) ==> (0 <= exhaleMask#_237_$_17[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys][perm$N]));
	assume exhaleMask#_237_$_18 == exhaleMask#_237_$_17[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys := exhaleMask#_237_$_17[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys][perm$R := exhaleMask#_237_$_17[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_237_$_18);
	assume wf(Heap_$_2,exhaleMask#_237_$_18,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_19 == exhaleMask#_237_$_18;
	if ($_$_condition_$17) { goto anon38_Then; } else { goto anon38_Else; }
anon37_Else:
	assume Heap_$_2[this,AVLTreeNode.right] == null;
	assume exhaleMask#_237_$_19 == exhaleMask#_237_$_17;
	if ($_$_condition_$18) { goto anon38_Then; } else { goto anon38_Else; }
anon38_Then:
	assume !(Heap_$_2[this,AVLTreeNode.right] == null);
	assert { :msg "  179.3: The precondition at 561.12 might not hold. The permission at 561.28 might not be positive." } Fractions(50) > 0;
	assert { :msg "  179.3: The precondition at 561.12 might not hold. Insufficient fraction at 561.28 for AVLTreeNode.balanceFactor." } (Fractions(50) <= exhaleMask#_237_$_19[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.balanceFactor][perm$R]) && ((Fractions(50) == exhaleMask#_237_$_19[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.balanceFactor][perm$R]) ==> (0 <= exhaleMask#_237_$_19[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.balanceFactor][perm$N]));
	assume exhaleMask#_237_$_20 == exhaleMask#_237_$_19[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.balanceFactor := exhaleMask#_237_$_19[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.balanceFactor][perm$R := exhaleMask#_237_$_19[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.balanceFactor][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_237_$_20);
	assume wf(Heap_$_2,exhaleMask#_237_$_20,ZeroMask);
	assume wf(Heap_$_2,Mask_$_5,ZeroMask);
	assume exhaleMask#_237_$_21 == exhaleMask#_237_$_20;
	goto anon24;
anon38_Else:
	assume Heap_$_2[this,AVLTreeNode.right] == null;
	assume exhaleMask#_237_$_21 == exhaleMask#_237_$_19;
	goto anon24;
anon24:
	assume IsGoodExhaleState(exhaleHeap#_236_$_0,Heap_$_2,exhaleMask#_237_$_21,ZeroMask);
	assume IsGoodMask(exhaleMask#_237_$_21);
	assume wf(exhaleHeap#_236_$_0,exhaleMask#_237_$_21,ZeroMask);
	assume !(this == null);
	assume wf(exhaleHeap#_236_$_0,exhaleMask#_237_$_21,ZeroMask);
	assume Fractions(100) > 0;
	assume Mask_$_6 == exhaleMask#_237_$_21[this,AVLTreeNode.valid := exhaleMask#_237_$_21[this,AVLTreeNode.valid][perm$R := exhaleMask#_237_$_21[this,AVLTreeNode.valid][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_6);
	assume IsGoodState(heapFragment(exhaleHeap#_236_$_0[this,AVLTreeNode.valid]));
	assume wf(exhaleHeap#_236_$_0,Mask_$_6,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_6,ZeroMask);
	assume !(this == null);
	assume wf(exhaleHeap#_236_$_0,Mask_$_6,ZeroMask);
	assume true;
	assume Fractions(50) > 0;
	assume Mask_$_7 == Mask_$_6[this,AVLTreeNode.height := Mask_$_6[this,AVLTreeNode.height][perm$R := Mask_$_6[this,AVLTreeNode.height][perm$R] + Fractions(50)]];
	assume IsGoodMask(Mask_$_7);
	assume IsGoodState(heapFragment(exhaleHeap#_236_$_0[this,AVLTreeNode.height]));
	assume wf(exhaleHeap#_236_$_0,Mask_$_7,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_7,ZeroMask);
	assume !(this == null);
	assume wf(exhaleHeap#_236_$_0,Mask_$_7,ZeroMask);
	assume true;
	assume Fractions(50) > 0;
	assume Mask_$_8 == Mask_$_7[this,AVLTreeNode.keys := Mask_$_7[this,AVLTreeNode.keys][perm$R := Mask_$_7[this,AVLTreeNode.keys][perm$R] + Fractions(50)]];
	assume IsGoodMask(Mask_$_8);
	assume IsGoodState(heapFragment(exhaleHeap#_236_$_0[this,AVLTreeNode.keys]));
	assume wf(exhaleHeap#_236_$_0,Mask_$_8,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_8,ZeroMask);
	assume !(this == null);
	assume wf(exhaleHeap#_236_$_0,Mask_$_8,ZeroMask);
	assume true;
	assume Fractions(50) > 0;
	assume Mask_$_9 == Mask_$_8[this,AVLTreeNode.balanceFactor := Mask_$_8[this,AVLTreeNode.balanceFactor][perm$R := Mask_$_8[this,AVLTreeNode.balanceFactor][perm$R] + Fractions(50)]];
	assume IsGoodMask(Mask_$_9);
	assume IsGoodState(heapFragment(exhaleHeap#_236_$_0[this,AVLTreeNode.balanceFactor]));
	assume wf(exhaleHeap#_236_$_0,Mask_$_9,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_9,ZeroMask);
	assume Seq#Equal(exhaleHeap#_236_$_0[this,AVLTreeNode.keys],Seq#Append(Seq#Append(ite(Heap_$_2[this,AVLTreeNode.left] == null,(Seq#Empty() : Seq (Integer) ),Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.keys]),Seq#Singleton(Heap_$_2[this,AVLTreeNode.key])),ite(Heap_$_2[this,AVLTreeNode.right] == null,(Seq#Empty() : Seq (Integer) ),Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.keys])));
	assume exhaleHeap#_236_$_0[this,AVLTreeNode.height] == ite(ite(Heap_$_2[this,AVLTreeNode.left] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height]) > ite(Heap_$_2[this,AVLTreeNode.right] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height]),ite(Heap_$_2[this,AVLTreeNode.left] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height]) + 1,ite(Heap_$_2[this,AVLTreeNode.right] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height]) + 1);
	assume exhaleHeap#_236_$_0[this,AVLTreeNode.balanceFactor] == (ite(Heap_$_2[this,AVLTreeNode.left] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.left],AVLTreeNode.height]) - ite(Heap_$_2[this,AVLTreeNode.right] == null,0,Heap_$_2[Heap_$_2[this,AVLTreeNode.right],AVLTreeNode.height]));
	assume IsGoodMask(Mask_$_9);
	assume wf(exhaleHeap#_236_$_0,Mask_$_9,ZeroMask);
	assert { :msg "  154.2: The postcondition at 168.11 might not hold. The expression at 168.11 might not evaluate to true." } exhaleHeap#_236_$_0[this,AVLTreeNode.height] == 1;
	assert { :msg "  154.2: The postcondition at 169.11 might not hold. The expression at 169.11 might not evaluate to true." } Seq#Equal(exhaleHeap#_236_$_0[this,AVLTreeNode.keys],Seq#Singleton(k#8));
	assert { :msg "  154.2: The postcondition at 170.11 might not hold. The expression at 170.11 might not evaluate to true." } exhaleHeap#_236_$_0[this,AVLTreeNode.balanceFactor] == 0;
	assert { :msg "  154.2: The postcondition at 172.11 might not hold. The expression at 172.11 might not evaluate to true." } Seq#Contains(exhaleHeap#_236_$_0[this,AVLTreeNode.keys],k#8);
	assert { :msg "  154.2: The postcondition at 163.11 might not hold. The permission at 163.11 might not be positive." } Fractions(100) > 0;
	assert { :msg "  154.2: The postcondition at 163.11 might not hold. Insufficient fraction at 163.11 for AVLTreeNode.valid." } (Fractions(100) <= Mask_$_9[this,AVLTreeNode.valid][perm$R]) && ((Fractions(100) == Mask_$_9[this,AVLTreeNode.valid][perm$R]) ==> (0 <= Mask_$_9[this,AVLTreeNode.valid][perm$N]));
	assume exhaleMask#_255_$_0 == Mask_$_9[this,AVLTreeNode.valid := Mask_$_9[this,AVLTreeNode.valid][perm$R := Mask_$_9[this,AVLTreeNode.valid][perm$R] - Fractions(100)]];
	if ($_$_condition_$19) { goto anon39_Then; } else { goto anon39_Else; }
anon39_Then:
	assume !CanRead(exhaleMask#_255_$_0,ZeroMask,this,AVLTreeNode.valid);
	assume exhaleHeap#_236_$_0[this,AVLTreeNode.valid] < exhaleHeap#_254_$_0[this,AVLTreeNode.valid];
	goto anon26;
anon39_Else:
	assume CanRead(exhaleMask#_255_$_0,ZeroMask,this,AVLTreeNode.valid);
	goto anon26;
anon26:
	assume IsGoodMask(exhaleMask#_255_$_0);
	assume wf(exhaleHeap#_236_$_0,exhaleMask#_255_$_0,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_9,ZeroMask);
	assert { :msg "  154.2: The postcondition at 164.11 might not hold. The permission at 164.11 might not be positive." } Fractions(50) > 0;
	assert { :msg "  154.2: The postcondition at 164.11 might not hold. Insufficient fraction at 164.11 for AVLTreeNode.keys." } (Fractions(50) <= exhaleMask#_255_$_0[this,AVLTreeNode.keys][perm$R]) && ((Fractions(50) == exhaleMask#_255_$_0[this,AVLTreeNode.keys][perm$R]) ==> (0 <= exhaleMask#_255_$_0[this,AVLTreeNode.keys][perm$N]));
	assume exhaleMask#_255_$_1 == exhaleMask#_255_$_0[this,AVLTreeNode.keys := exhaleMask#_255_$_0[this,AVLTreeNode.keys][perm$R := exhaleMask#_255_$_0[this,AVLTreeNode.keys][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_255_$_1);
	assume wf(exhaleHeap#_236_$_0,exhaleMask#_255_$_1,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_9,ZeroMask);
	assert { :msg "  154.2: The postcondition at 165.11 might not hold. The permission at 165.11 might not be positive." } Fractions(50) > 0;
	assert { :msg "  154.2: The postcondition at 165.11 might not hold. Insufficient fraction at 165.11 for AVLTreeNode.height." } (Fractions(50) <= exhaleMask#_255_$_1[this,AVLTreeNode.height][perm$R]) && ((Fractions(50) == exhaleMask#_255_$_1[this,AVLTreeNode.height][perm$R]) ==> (0 <= exhaleMask#_255_$_1[this,AVLTreeNode.height][perm$N]));
	assume exhaleMask#_255_$_2 == exhaleMask#_255_$_1[this,AVLTreeNode.height := exhaleMask#_255_$_1[this,AVLTreeNode.height][perm$R := exhaleMask#_255_$_1[this,AVLTreeNode.height][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_255_$_2);
	assume wf(exhaleHeap#_236_$_0,exhaleMask#_255_$_2,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_9,ZeroMask);
	assert { :msg "  154.2: The postcondition at 166.11 might not hold. The permission at 166.11 might not be positive." } Fractions(50) > 0;
	assert { :msg "  154.2: The postcondition at 166.11 might not hold. Insufficient fraction at 166.11 for AVLTreeNode.balanceFactor." } (Fractions(50) <= exhaleMask#_255_$_2[this,AVLTreeNode.balanceFactor][perm$R]) && ((Fractions(50) == exhaleMask#_255_$_2[this,AVLTreeNode.balanceFactor][perm$R]) ==> (0 <= exhaleMask#_255_$_2[this,AVLTreeNode.balanceFactor][perm$N]));
	assume exhaleMask#_255_$_3 == exhaleMask#_255_$_2[this,AVLTreeNode.balanceFactor := exhaleMask#_255_$_2[this,AVLTreeNode.balanceFactor][perm$R := exhaleMask#_255_$_2[this,AVLTreeNode.balanceFactor][perm$R] - Fractions(50)]];
	assume IsGoodMask(exhaleMask#_255_$_3);
	assume wf(exhaleHeap#_236_$_0,exhaleMask#_255_$_3,ZeroMask);
	assume wf(exhaleHeap#_236_$_0,Mask_$_9,ZeroMask);
	assume IsGoodExhaleState(exhaleHeap#_254_$_0,exhaleHeap#_236_$_0,exhaleMask#_255_$_3,ZeroMask);
	assume IsGoodMask(exhaleMask#_255_$_3);
	assume wf(exhaleHeap#_254_$_0,exhaleMask#_255_$_3,ZeroMask);
	assert { :msg "  154.2: Method might lock/unlock more than allowed." } (forall  lk#_260 : ref :: {exhaleHeap#_254_$_0[lk#_260,held]} {exhaleHeap#_254_$_0[lk#_260,rdheld]} ( (((0 < exhaleHeap#_254_$_0[lk#_260,held]) <==> (0 < Heap[lk#_260,held])) && (exhaleHeap#_254_$_0[lk#_260,rdheld] <==> Heap[lk#_260,rdheld])) || false ));
	assert { :msg "  154.2: Method body is not allowed to leave any debt." } (forall  ch : ref :: ( (ch == null) || (0 <= ZeroCredits[ch]) ));
	goto $exit;
}
