type Integer = int;
type Boolean = bool;
type HeapType = <a>[ref,Field (a)]a;
type MaskType = <a>[ref,Field (a)][PermissionComponent]int;
type CreditsType = [ref]int;
type ArgSeq = <T>[int]T;
type string = int;
type Field m0;
type ref;
type PermissionComponent;
type PartialHeapType;
type ModuleName;
type TypeName;
type Mu;
const null : ref;
const unique perm$R : PermissionComponent;
const unique perm$N : PermissionComponent;
const Permission$denominator : int;
const Permission$FullFraction : int;
const Permission$Zero : [PermissionComponent]int;
const Permission$Full : [PermissionComponent]int;
const ZeroMask : MaskType;
const unique joinable : Field (int);
const unique token#t : TypeName;
const unique forkK : Field (int);
const channelK : int;
const monitorK : int;
const predicateK : int;
const emptyPartialHeap : PartialHeapType;
const CurrentModule : ModuleName;
const CanAssumeFunctionDefs : bool;
const unique mu : Field (Mu);
const $LockBottom : Mu;
const unique held : Field (int);
const unique rdheld : Field (bool);
const ZeroCredits : CreditsType;
const unique Node#t : TypeName;
const unique module#default : ModuleName;
const unique Node.next : Field (ref);
const unique Node.prev : Field (ref);
const unique Node.inv : Field (int);
const unique Node.invLeft : Field (int);
const unique Node.invRight : Field (int);
const $old_Heap : HeapType;
const $old_Mask : MaskType;
const $old_SecMask : MaskType;
const $old_Credits : CreditsType;
function Fractions(int) : int;
function IsGoodState(PartialHeapType) : bool;
function combine(PartialHeapType,PartialHeapType) : PartialHeapType;
function heapFragment <T> (T) : PartialHeapType;
function dtype(ref) : TypeName;
function MuBelow(Mu,Mu) : bool;
function Acquire$Heap(int) : HeapType;
function Acquire$Mask(int) : MaskType;
function Acquire$SecMask(int) : MaskType;
function Acquire$Credits(int) : CreditsType;
function LastSeen$Heap(Mu,int) : HeapType;
function LastSeen$Mask(Mu,int) : MaskType;
function LastSeen$SecMask(Mu,int) : MaskType;
function LastSeen$Credits(Mu,int) : CreditsType;
function wf(HeapType,MaskType,MaskType) : bool;
function IsGoodInhaleState(HeapType,HeapType,MaskType,MaskType) : bool;
function IsGoodExhaleState(HeapType,HeapType,MaskType,MaskType) : bool;
function {:expand  false} CanRead <T> (MaskType,MaskType,ref,Field (T)) : bool;
function {:expand  false} CanReadForSure <T> (MaskType,ref,Field (T)) : bool;
function {:expand  false} CanWrite <T> (MaskType,ref,Field (T)) : bool;
function {:expand  true} IsGoodMask(MaskType) : bool;
function DecPerm <T> (MaskType,ref,Field (T),int) : MaskType;
function DecEpsilons <T> (MaskType,ref,Field (T),int) : MaskType;
function IncPerm <T> (MaskType,ref,Field (T),int) : MaskType;
function IncEpsilons <T> (MaskType,ref,Field (T),int) : MaskType;
function Havocing <T,U> (HeapType,ref,Field (T),U) : HeapType;
function Call$Heap(int) : HeapType;
function Call$Mask(int) : MaskType;
function Call$SecMask(int) : MaskType;
function Call$Credits(int) : CreditsType;
function Call$Args(int) : ArgSeq;
function EmptyMask(MaskType) : bool;
function EmptyCredits(CreditsType) : bool;
function NonPredicateField <T> (Field (T)) : bool;
function PredicateField <T> (Field (T)) : bool;
function submask(MaskType,MaskType) : bool;
function ite <T> (bool,T,T) : T;
function #Node.inv#trigger(ref) : bool;
function #Node.invLeft#trigger(ref) : bool;
function #Node.invRight#trigger(ref) : bool;
var Heap : HeapType;
var Mask : MaskType;
var SecMask : MaskType;
var Credits : CreditsType;
var predicateK#_27 : int;
var Mask_$_0 : MaskType;
var Mask_$_1 : MaskType;
var Mask_$_2 : MaskType;
var Mask_$_4 : MaskType;
var SecMask_$_5 : MaskType;
var SecMask_$_11 : MaskType;
var Mask_$_6 : MaskType;
var Mask_$_5 : MaskType;
var predRec#_63_$_0 : ref;
var predVer#_64_$_0 : int;
var unfoldingK#_71 : int;
var unfoldingMask#_67_$_0 : MaskType;
var unfoldingHeap#_66_$_1 : HeapType;
var unfoldingMask#_67_$_1 : MaskType;
var unfoldingMask#_67_$_2 : MaskType;
var unfoldingMask#_67_$_3 : MaskType;
var unfoldingMask#_67_$_5 : MaskType;
var unfoldingSecMask#_68_$_5 : MaskType;
var SecMask_$_6 : MaskType;
var SecMask_$_7 : MaskType;
var SecMask_$_8 : MaskType;
var SecMask_$_10 : MaskType;
var SecMask_$_9 : MaskType;
var unfoldingMask#_67_$_4 : MaskType;
var predRec#_83_$_0 : ref;
var predVer#_84_$_0 : int;
var unfoldingSecMask#_68_$_0 : MaskType;
var unfoldingSecMask#_68_$_1 : MaskType;
var unfoldingSecMask#_68_$_2 : MaskType;
var unfoldingSecMask#_68_$_4 : MaskType;
var unfoldingSecMask#_68_$_3 : MaskType;
var oldVers#_81_$_0 : int;
var unfoldingHeap#_66_$_0 : HeapType;
var newVers#_82_$_0 : int;
var Mask_$_3 : MaskType;
var predRec#_28_$_0 : ref;
var predVer#_29_$_0 : int;
var unfoldingK#_36 : int;
var unfoldingMask#_32_$_0 : MaskType;
var unfoldingHeap#_31_$_1 : HeapType;
var unfoldingMask#_32_$_1 : MaskType;
var unfoldingMask#_32_$_2 : MaskType;
var unfoldingMask#_32_$_3 : MaskType;
var unfoldingMask#_32_$_5 : MaskType;
var unfoldingSecMask#_33_$_5 : MaskType;
var SecMask_$_0 : MaskType;
var SecMask_$_1 : MaskType;
var SecMask_$_2 : MaskType;
var SecMask_$_4 : MaskType;
var SecMask_$_3 : MaskType;
var unfoldingMask#_32_$_4 : MaskType;
var predRec#_48_$_0 : ref;
var predVer#_49_$_0 : int;
var unfoldingSecMask#_33_$_0 : MaskType;
var unfoldingSecMask#_33_$_1 : MaskType;
var unfoldingSecMask#_33_$_2 : MaskType;
var unfoldingSecMask#_33_$_4 : MaskType;
var unfoldingSecMask#_33_$_3 : MaskType;
var oldVers#_46_$_0 : int;
var unfoldingHeap#_31_$_0 : HeapType;
var newVers#_47_$_0 : int;
var predRec#_28 : ref;
var predFlag#_30 : bool;
var predVer#_29 : int;
var predFlag#_35 : bool;
var unfoldingHeap#_31 : HeapType;
var unfoldingMask#_32 : MaskType;
var unfoldingSecMask#_33 : MaskType;
var unfoldingCredits#_34 : CreditsType;
var oldVers#_46 : int;
var newVers#_47 : int;
var predRec#_48 : ref;
var predFlag#_50 : bool;
var predVer#_49 : int;
var predRec#_63 : ref;
var predFlag#_65 : bool;
var predVer#_64 : int;
var predFlag#_70 : bool;
var unfoldingHeap#_66 : HeapType;
var unfoldingMask#_67 : MaskType;
var unfoldingSecMask#_68 : MaskType;
var unfoldingCredits#_69 : CreditsType;
var oldVers#_81 : int;
var newVers#_82 : int;
var predRec#_83 : ref;
var predFlag#_85 : bool;
var predVer#_84 : int;
procedure Node.inv$checkDefinedness (this : ref)
{
	var predicateK#_27 : int;
	var predRec#_28 : ref;
	var predFlag#_30 : bool;
	var predVer#_29 : int;
	var unfoldingK#_36 : int;
	var predFlag#_35 : bool;
	var unfoldingHeap#_31 : HeapType;
	var unfoldingMask#_32 : MaskType;
	var unfoldingSecMask#_33 : MaskType;
	var unfoldingCredits#_34 : CreditsType;
	var oldVers#_46 : int;
	var newVers#_47 : int;
	var predRec#_48 : ref;
	var predFlag#_50 : bool;
	var predVer#_49 : int;
	var predRec#_63 : ref;
	var predFlag#_65 : bool;
	var predVer#_64 : int;
	var unfoldingK#_71 : int;
	var predFlag#_70 : bool;
	var unfoldingHeap#_66 : HeapType;
	var unfoldingMask#_67 : MaskType;
	var unfoldingSecMask#_68 : MaskType;
	var unfoldingCredits#_69 : CreditsType;
	var oldVers#_81 : int;
	var newVers#_82 : int;
	var predRec#_83 : ref;
	var predFlag#_85 : bool;
	var predVer#_84 : int;
	var Mask_$_0 : MaskType;
	var Mask_$_1 : MaskType;
	var Mask_$_2 : MaskType;
	var Mask_$_3 : MaskType;
	var predRec#_28_$_0 : ref;
	var predVer#_29_$_0 : int;
	var unfoldingMask#_32_$_0 : MaskType;
	var oldVers#_46_$_0 : int;
	var newVers#_47_$_0 : int;
	var unfoldingHeap#_31_$_0 : HeapType;
	var unfoldingHeap#_31_$_1 : HeapType;
	var unfoldingMask#_32_$_1 : MaskType;
	var unfoldingMask#_32_$_2 : MaskType;
	var unfoldingMask#_32_$_3 : MaskType;
	var unfoldingMask#_32_$_4 : MaskType;
	var predRec#_48_$_0 : ref;
	var predVer#_49_$_0 : int;
	var unfoldingSecMask#_33_$_0 : MaskType;
	var unfoldingSecMask#_33_$_1 : MaskType;
	var unfoldingSecMask#_33_$_2 : MaskType;
	var unfoldingSecMask#_33_$_3 : MaskType;
	var unfoldingSecMask#_33_$_4 : MaskType;
	var unfoldingMask#_32_$_5 : MaskType;
	var unfoldingSecMask#_33_$_5 : MaskType;
	var SecMask_$_0 : MaskType;
	var SecMask_$_1 : MaskType;
	var SecMask_$_2 : MaskType;
	var SecMask_$_3 : MaskType;
	var SecMask_$_4 : MaskType;
	var Mask_$_4 : MaskType;
	var SecMask_$_5 : MaskType;
	var Mask_$_5 : MaskType;
	var predRec#_63_$_0 : ref;
	var predVer#_64_$_0 : int;
	var unfoldingMask#_67_$_0 : MaskType;
	var oldVers#_81_$_0 : int;
	var newVers#_82_$_0 : int;
	var unfoldingHeap#_66_$_0 : HeapType;
	var unfoldingHeap#_66_$_1 : HeapType;
	var unfoldingMask#_67_$_1 : MaskType;
	var unfoldingMask#_67_$_2 : MaskType;
	var unfoldingMask#_67_$_3 : MaskType;
	var unfoldingMask#_67_$_4 : MaskType;
	var predRec#_83_$_0 : ref;
	var predVer#_84_$_0 : int;
	var unfoldingSecMask#_68_$_0 : MaskType;
	var unfoldingSecMask#_68_$_1 : MaskType;
	var unfoldingSecMask#_68_$_2 : MaskType;
	var unfoldingSecMask#_68_$_3 : MaskType;
	var unfoldingSecMask#_68_$_4 : MaskType;
	var unfoldingMask#_67_$_5 : MaskType;
	var unfoldingSecMask#_68_$_5 : MaskType;
	var SecMask_$_6 : MaskType;
	var SecMask_$_7 : MaskType;
	var SecMask_$_8 : MaskType;
	var SecMask_$_9 : MaskType;
	var SecMask_$_10 : MaskType;
	var SecMask_$_11 : MaskType;
	var Mask_$_6 : MaskType;
	var $_$_condition : bool;
	var $_$_condition_$0 : bool;
	var $_$_condition_$1 : bool;
	var $_$_condition_$2 : bool;
	var $_$_condition_$3 : bool;
	var $_$_condition_$4 : bool;
	var $_$_condition_$5 : bool;
	var $_$_condition_$6 : bool;
	var $_$_condition_$7 : bool;
	var $_$_condition_$8 : bool;
	var $_$_condition_$9 : bool;
	var $_$_condition_$10 : bool;
	var $_$_condition_$11 : bool;
	var $_$_condition_$12 : bool;
	var $_$_condition_$13 : bool;
	var $_$_condition_$14 : bool;
$start:
	assume Permission$denominator > 0;
	assume (Permission$Zero[perm$R] == 0) && (Permission$Zero[perm$N] == 0);
	assume (Permission$Full[perm$R] == Permission$FullFraction) && (Permission$Full[perm$N] == 0);
	assume (forall<T> o : ref, f : Field (T) , pc : PermissionComponent :: ( ZeroMask[o,f][pc] == 0 ));
	assume IsGoodMask(ZeroMask);
	assume NonPredicateField(joinable);
	assume NonPredicateField(forkK);
	assume (forall  n : Integer :: {Fractions(n)} ( Fractions(n) == (n * Permission$denominator) ));
	assume (forall  x : Integer, y : Integer :: ( ((0 <= x) && (x <= y)) ==> (Fractions(x) <= Fractions(y)) ));
	assume Permission$FullFraction == Fractions(100);
	assume (0 < channelK) && ((1000 * channelK) < Fractions(1));
	assume (0 < monitorK) && ((1000 * monitorK) < Fractions(1));
	assume (0 < predicateK) && ((1000 * predicateK) < Fractions(1));
	assume (predicateK == channelK) && (channelK == monitorK);
	assume (forall  a : PartialHeapType, b : PartialHeapType :: {IsGoodState(combine(a,b))} ( IsGoodState(combine(a,b)) <==> (IsGoodState(a) && IsGoodState(b)) ));
	assume IsGoodState(emptyPartialHeap);
	assume NonPredicateField(mu);
	assume (forall  m : Mu, n_$0 : Mu :: {MuBelow(m,n_$0),MuBelow(n_$0,m)} ( !(MuBelow(m,n_$0) && MuBelow(n_$0,m)) ));
	assume (forall  m_$0 : Mu, n_$1 : Mu, o_$0 : Mu :: {MuBelow(m_$0,n_$1),MuBelow(n_$1,o_$0)} ( (MuBelow(m_$0,n_$1) && MuBelow(n_$1,o_$0)) ==> MuBelow(m_$0,o_$0) ));
	assume (forall  m_$1 : Mu, n_$2 : Mu :: ( MuBelow(m_$1,n_$2) ==> (!(n_$2 == $LockBottom)) ));
	assume NonPredicateField(held);
	assume NonPredicateField(rdheld);
	assume (forall  ih : HeapType, h : HeapType, m_$2 : MaskType, sm : MaskType :: {IsGoodInhaleState(ih,h,m_$2,sm)} ( IsGoodInhaleState(ih,h,m_$2,sm) <==> ((((((forall<T> o_$1 : ref, f_$0 : Field (T)  :: {ih[o_$1,f_$0]} ( CanRead(m_$2,sm,o_$1,f_$0) ==> (ih[o_$1,f_$0] == h[o_$1,f_$0]) ))) && ((forall  o_$2 : ref :: {ih[o_$2,held]} ( (0 < ih[o_$2,held]) <==> (0 < h[o_$2,held]) )))) && ((forall  o_$3 : ref :: {ih[o_$3,rdheld]} ( ih[o_$3,rdheld] <==> h[o_$3,rdheld] )))) && ((forall  o_$4 : ref :: {h[o_$4,held]} ( (0 < h[o_$4,held]) ==> (ih[o_$4,mu] == h[o_$4,mu]) )))) && ((forall  o_$5 : ref :: {h[o_$5,rdheld]} ( h[o_$5,rdheld] ==> (ih[o_$5,mu] == h[o_$5,mu]) )))) ));
	assume (forall  eh : HeapType, h_$0 : HeapType, m_$3 : MaskType, sm_$0 : MaskType :: {IsGoodExhaleState(eh,h_$0,m_$3,sm_$0)} ( IsGoodExhaleState(eh,h_$0,m_$3,sm_$0) <==> (((((((((forall<T> o_$6 : ref, f_$1 : Field (T)  :: {eh[o_$6,f_$1]} ( CanRead(m_$3,sm_$0,o_$6,f_$1) ==> (eh[o_$6,f_$1] == h_$0[o_$6,f_$1]) ))) && ((forall  o_$7 : ref :: {eh[o_$7,held]} ( (0 < eh[o_$7,held]) <==> (0 < h_$0[o_$7,held]) )))) && ((forall  o_$8 : ref :: {eh[o_$8,rdheld]} ( eh[o_$8,rdheld] <==> h_$0[o_$8,rdheld] )))) && ((forall  o_$9 : ref :: {h_$0[o_$9,held]} ( (0 < h_$0[o_$9,held]) ==> (eh[o_$9,mu] == h_$0[o_$9,mu]) )))) && ((forall  o_$10 : ref :: {h_$0[o_$10,rdheld]} ( h_$0[o_$10,rdheld] ==> (eh[o_$10,mu] == h_$0[o_$10,mu]) )))) && ((forall  o_$11 : ref :: {h_$0[o_$11,forkK]} {eh[o_$11,forkK]} ( h_$0[o_$11,forkK] == eh[o_$11,forkK] )))) && ((forall  o_$12 : ref :: {h_$0[o_$12,held]} {eh[o_$12,held]} ( h_$0[o_$12,held] == eh[o_$12,held] )))) && ((forall  o_$13 : ref, f_$2 : Field (Integer)  :: {eh[o_$13,f_$2],PredicateField(f_$2)} ( PredicateField(f_$2) ==> (h_$0[o_$13,f_$2] <= eh[o_$13,f_$2]) )))) ));
	assume (forall<T> m_$4 : MaskType, sm_$1 : MaskType, obj : ref, f_$3 : Field (T)  :: {CanRead(m_$4,sm_$1,obj,f_$3)} {:expand  false}( CanRead(m_$4,sm_$1,obj,f_$3) <==> ((((0 < m_$4[obj,f_$3][perm$R]) || (0 < m_$4[obj,f_$3][perm$N])) || (0 < sm_$1[obj,f_$3][perm$R])) || (0 < sm_$1[obj,f_$3][perm$N])) ));
	assume (forall<T> m_$5 : MaskType, obj_$0 : ref, f_$4 : Field (T)  :: {CanReadForSure(m_$5,obj_$0,f_$4)} {:expand  false}( CanReadForSure(m_$5,obj_$0,f_$4) <==> ((0 < m_$5[obj_$0,f_$4][perm$R]) || (0 < m_$5[obj_$0,f_$4][perm$N])) ));
	assume (forall<T> m_$6 : MaskType, obj_$1 : ref, f_$5 : Field (T)  :: {CanWrite(m_$6,obj_$1,f_$5)} {:expand  false}( CanWrite(m_$6,obj_$1,f_$5) <==> ((m_$6[obj_$1,f_$5][perm$R] == Permission$FullFraction) && (m_$6[obj_$1,f_$5][perm$N] == 0)) ));
	assume (forall  m_$7 : MaskType :: {IsGoodMask(m_$7)} {:expand  true}( IsGoodMask(m_$7) <==> ((forall<T> o_$14 : ref, f_$6 : Field (T)  :: ( ((0 <= m_$7[o_$14,f_$6][perm$R]) && (NonPredicateField(f_$6) ==> ((m_$7[o_$14,f_$6][perm$R] <= Permission$FullFraction) && ((0 < m_$7[o_$14,f_$6][perm$N]) ==> (m_$7[o_$14,f_$6][perm$R] < Permission$FullFraction))))) && ((m_$7[o_$14,f_$6][perm$N] < 0) ==> (0 < m_$7[o_$14,f_$6][perm$R])) ))) ));
	assume (forall  h_$1 : HeapType, m_$8 : MaskType, sm_$2 : MaskType, o_$15 : ref, q : ref :: {wf(h_$1,m_$8,sm_$2),h_$1[o_$15,mu],h_$1[q,mu]} ( (((wf(h_$1,m_$8,sm_$2) && (!(o_$15 == q))) && ((0 < h_$1[o_$15,held]) || h_$1[o_$15,rdheld])) && ((0 < h_$1[q,held]) || h_$1[q,rdheld])) ==> (!(h_$1[o_$15,mu] == h_$1[q,mu])) ));
	assume (forall<T,U> m_$9 : MaskType, o_$16 : ref, f_$7 : Field (T) , howMuch : Integer, q_$0 : ref, g : Field (U)  :: {DecPerm(m_$9,o_$16,f_$7,howMuch)[q_$0,g][perm$R]} ( DecPerm(m_$9,o_$16,f_$7,howMuch)[q_$0,g][perm$R] == ite((o_$16 == q_$0) && (f_$7 == g),m_$9[q_$0,g][perm$R] - howMuch,m_$9[q_$0,g][perm$R]) ));
	assume (forall<T,U> m_$10 : MaskType, o_$17 : ref, f_$8 : Field (T) , howMuch_$0 : Integer, q_$1 : ref, g_$0 : Field (U)  :: {DecPerm(m_$10,o_$17,f_$8,howMuch_$0)[q_$1,g_$0][perm$N]} ( DecEpsilons(m_$10,o_$17,f_$8,howMuch_$0)[q_$1,g_$0][perm$N] == ite((o_$17 == q_$1) && (f_$8 == g_$0),m_$10[q_$1,g_$0][perm$N] - howMuch_$0,m_$10[q_$1,g_$0][perm$N]) ));
	assume (forall<T,U> m_$11 : MaskType, o_$18 : ref, f_$9 : Field (T) , howMuch_$1 : Integer, q_$2 : ref, g_$1 : Field (U)  :: {IncPerm(m_$11,o_$18,f_$9,howMuch_$1)[q_$2,g_$1][perm$R]} ( IncPerm(m_$11,o_$18,f_$9,howMuch_$1)[q_$2,g_$1][perm$R] == ite((o_$18 == q_$2) && (f_$9 == g_$1),m_$11[q_$2,g_$1][perm$R] + howMuch_$1,m_$11[q_$2,g_$1][perm$R]) ));
	assume (forall<T,U> m_$12 : MaskType, o_$19 : ref, f_$10 : Field (T) , howMuch_$2 : Integer, q_$3 : ref, g_$2 : Field (U)  :: {IncPerm(m_$12,o_$19,f_$10,howMuch_$2)[q_$3,g_$2][perm$N]} ( IncEpsilons(m_$12,o_$19,f_$10,howMuch_$2)[q_$3,g_$2][perm$N] == ite((o_$19 == q_$3) && (f_$10 == g_$2),m_$12[q_$3,g_$2][perm$N] + howMuch_$2,m_$12[q_$3,g_$2][perm$N]) ));
	assume (forall<T,U> h_$2 : HeapType, o_$20 : ref, f_$11 : Field (T) , newValue : U, q_$4 : ref, g_$3 : Field (U)  :: {Havocing(h_$2,o_$20,f_$11,newValue)[q_$4,g_$3]} ( Havocing(h_$2,o_$20,f_$11,newValue)[q_$4,g_$3] == ite((o_$20 == q_$4) && (f_$11 == g_$3),newValue,h_$2[q_$4,g_$3]) ));
	assume (forall  m_$13 : MaskType :: {EmptyMask(m_$13)} ( EmptyMask(m_$13) <==> ((forall<T> o_$21 : ref, f_$12 : Field (T)  :: ( NonPredicateField(f_$12) ==> ((m_$13[o_$21,f_$12][perm$R] <= 0) && (m_$13[o_$21,f_$12][perm$N] <= 0)) ))) ));
	assume (forall  o_$22 : ref :: ( ZeroCredits[o_$22] == 0 ));
	assume (forall  c : CreditsType :: {EmptyCredits(c)} ( EmptyCredits(c) <==> ((forall  o_$23 : ref :: ( (!(o_$23 == null)) ==> (c[o_$23] == 0) ))) ));
	assume (forall<T> f_$13 : Field (T)  :: ( NonPredicateField(f_$13) ==> (!PredicateField(f_$13)) ));
	assume (forall<T> f_$14 : Field (T)  :: ( PredicateField(f_$14) ==> (!NonPredicateField(f_$14)) ));
	assume (forall  m1 : MaskType, m2 : MaskType :: {submask(m1,m2)} ( submask(m1,m2) <==> ((forall<T> o_$24 : ref, f_$15 : Field (T)  :: ( (m1[o_$24,f_$15][perm$R] < m2[o_$24,f_$15][perm$R]) || ((m1[o_$24,f_$15][perm$R] == m2[o_$24,f_$15][perm$R]) && (m1[o_$24,f_$15][perm$N] <= m2[o_$24,f_$15][perm$N])) ))) ));
	assume (forall<T> con : Boolean, a_$0 : T, b_$0 : T :: {ite(con,a_$0,b_$0)} ( con ==> (ite(con,a_$0,b_$0) == a_$0) ));
	assume (forall<T> con_$0 : Boolean, a_$1 : T, b_$1 : T :: {ite(con_$0,a_$1,b_$1)} ( (!con_$0) ==> (ite(con_$0,a_$1,b_$1) == b_$1) ));
	assume (forall  x_$0 : Integer, y_$0 : Integer :: {x_$0 mod y_$0} {x_$0 div y_$0} ( (x_$0 mod y_$0) == (x_$0 - ((x_$0 div y_$0) * y_$0)) ));
	assume (forall  x_$1 : Integer, y_$1 : Integer :: {x_$1 mod y_$1} ( (0 < y_$1) ==> ((0 <= (x_$1 mod y_$1)) && ((x_$1 mod y_$1) < y_$1)) ));
	assume (forall  x_$2 : Integer, y_$2 : Integer :: {x_$2 mod y_$2} ( (y_$2 < 0) ==> ((y_$2 < (x_$2 mod y_$2)) && ((x_$2 mod y_$2) <= 0)) ));
	assume (forall  a_$2 : Integer, b_$2 : Integer, d : Integer :: {a_$2 mod d,b_$2 mod d} ( (((2 <= d) && ((a_$2 mod d) == (b_$2 mod d))) && (a_$2 < b_$2)) ==> ((a_$2 + d) <= b_$2) ));
	assume NonPredicateField(Node.next);
	assume NonPredicateField(Node.prev);
	assume PredicateField(Node.inv);
	assume PredicateField(Node.invLeft);
	assume PredicateField(Node.invRight);
	goto PreconditionGeneratedEntry;
$exit:
	assume false;
PreconditionGeneratedEntry:
	assume IsGoodMask(Mask);
	assume IsGoodMask(SecMask);
	assume (this == null) || (dtype(this) == Node#t);
	assume !(this == null);
	assume wf(Heap,Mask,SecMask);
	goto anon0;
anon0:
	assume (0 < predicateK#_27) && ((1000 * predicateK#_27) < Fractions(1));
	assume !(this == null);
	assume wf(Heap,ZeroMask,ZeroMask);
	assume (Heap[this,Node.prev] == null) || (dtype(Heap[this,Node.prev]) == Node#t);
	assume 1 > 0;
	assume Mask_$_0 == ZeroMask[this,Node.prev := ZeroMask[this,Node.prev][perm$N := ZeroMask[this,Node.prev][perm$N] + 1]];
	assume wf(Heap,Mask_$_0,ZeroMask);
	assume IsGoodMask(Mask_$_0);
	assume IsGoodState(heapFragment(Heap[this,Node.prev]));
	assume wf(Heap,Mask_$_0,ZeroMask);
	assume wf(Heap,Mask_$_0,ZeroMask);
	assume !(this == null);
	assume wf(Heap,Mask_$_0,ZeroMask);
	assume (Heap[this,Node.next] == null) || (dtype(Heap[this,Node.next]) == Node#t);
	assume 1 > 0;
	assume Mask_$_1 == Mask_$_0[this,Node.next := Mask_$_0[this,Node.next][perm$N := Mask_$_0[this,Node.next][perm$N] + 1]];
	assume wf(Heap,Mask_$_1,ZeroMask);
	assume IsGoodMask(Mask_$_1);
	assume IsGoodState(heapFragment(Heap[this,Node.next]));
	assume wf(Heap,Mask_$_1,ZeroMask);
	assume wf(Heap,Mask_$_1,ZeroMask);
	assume !(this == null);
	assume wf(Heap,Mask_$_1,ZeroMask);
	assume true;
	assume 1 > 0;
	assume Mask_$_2 == Mask_$_1[this,mu := Mask_$_1[this,mu][perm$N := Mask_$_1[this,mu][perm$N] + 1]];
	assume wf(Heap,Mask_$_2,ZeroMask);
	assume IsGoodMask(Mask_$_2);
	assume IsGoodState(heapFragment(Heap[this,mu]));
	assume wf(Heap,Mask_$_2,ZeroMask);
	assume wf(Heap,Mask_$_2,ZeroMask);
	assert { :msg "  18.10: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  18.10: Location might not be readable." } true ==> CanRead(Mask_$_2,ZeroMask,this,Node.prev);
	if ($_$_condition) { goto anon105_Then; } else { goto anon105_Else; }
anon105_Then:
	assume !(Heap[this,Node.prev] == null);
	assert { :msg "  18.25: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  18.25: Location might not be readable." } true ==> CanRead(Mask_$_2,ZeroMask,this,Node.prev);
	assert { :msg "  18.25: Receiver might be null." } !(Heap[this,Node.prev] == null);
	assert { :msg "  18.25: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  18.25: Location might not be readable." } true ==> CanRead(Mask_$_2,ZeroMask,this,Node.prev);
	assume !(Heap[this,Node.prev] == null);
	assume wf(Heap,Mask_$_2,ZeroMask);
	assume Fractions(100) > 0;
	assume Mask_$_3 == Mask_$_2[Heap[this,Node.prev],Node.invLeft := Mask_$_2[Heap[this,Node.prev],Node.invLeft][perm$R := Mask_$_2[Heap[this,Node.prev],Node.invLeft][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_3);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.prev],Node.invLeft]));
	assume wf(Heap,Mask_$_3,ZeroMask);
	assume wf(Heap,Mask_$_3,ZeroMask);
	assume predRec#_28_$_0 == Heap[this,Node.prev];
	assume #Node.invLeft#trigger(Heap[this,Node.prev]);
	assume predVer#_29_$_0 == Heap[Heap[this,Node.prev],Node.invLeft];
	assume (0 < unfoldingK#_36) && ((1000 * unfoldingK#_36) < Fractions(1));
	assert { :msg "  18.51: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  18.51: Location might not be readable." } true ==> CanRead(Mask_$_3,ZeroMask,this,Node.prev);
	assert { :msg "  18.51: Receiver might be null." } true ==> (!(Heap[this,Node.prev] == null));
	assume wf(Heap,Mask_$_3,ZeroMask);
	assert { :msg "  18.41: Unfolding might fail. The permission at 18.51 might not be positive." } Fractions(100) > 0;
	assert { :msg "  18.41: Unfolding might fail. Insufficient fraction at 18.51 for Node.invLeft." } (Fractions(100) <= Mask_$_3[Heap[this,Node.prev],Node.invLeft][perm$R]) && ((Fractions(100) == Mask_$_3[Heap[this,Node.prev],Node.invLeft][perm$R]) ==> (0 <= Mask_$_3[Heap[this,Node.prev],Node.invLeft][perm$N]));
	assume unfoldingMask#_32_$_0 == Mask_$_3[Heap[this,Node.prev],Node.invLeft := Mask_$_3[Heap[this,Node.prev],Node.invLeft][perm$R := Mask_$_3[Heap[this,Node.prev],Node.invLeft][perm$R] - Fractions(100)]];
	if ($_$_condition_$0) { goto anon106_Then; } else { goto anon106_Else; }
anon105_Else:
	assume Heap[this,Node.prev] == null;
	assume Mask_$_4 == Mask_$_2;
	assume SecMask_$_5 == ZeroMask;
	goto anon52;
anon106_Then:
	assume false;
	goto $exit;
anon106_Else:
	assume !false;
	if ($_$_condition_$1) { goto anon113_Then; } else { goto anon113_Else; }
anon52:
	assert { :msg "  19.10: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  19.10: Location might not be readable." } true ==> CanRead(Mask_$_4,SecMask_$_5,this,Node.next);
	if ($_$_condition_$7) { goto anon131_Then; } else { goto anon131_Else; }
anon113_Then:
	assume !CanRead(unfoldingMask#_32_$_0,ZeroMask,Heap[this,Node.prev],Node.invLeft);
	assume oldVers#_46_$_0 == Heap[Heap[this,Node.prev],Node.invLeft];
	assume unfoldingHeap#_31_$_0 == Heap[Heap[this,Node.prev],Node.invLeft := newVers#_47_$_0];
	assume oldVers#_46_$_0 < unfoldingHeap#_31_$_0[unfoldingHeap#_31_$_0[this,Node.prev],Node.invLeft];
	assume unfoldingHeap#_31_$_1 == unfoldingHeap#_31_$_0;
	goto anon17;
anon113_Else:
	assume CanRead(unfoldingMask#_32_$_0,ZeroMask,Heap[this,Node.prev],Node.invLeft);
	assume unfoldingHeap#_31_$_1 == Heap;
	goto anon17;
anon17:
	assume IsGoodMask(unfoldingMask#_32_$_0);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_0,ZeroMask);
	assume IsGoodMask(unfoldingMask#_32_$_0);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_0,ZeroMask);
	assume !(unfoldingHeap#_31_$_1[this,Node.prev] == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_0,ZeroMask);
	assume (unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev] == null) || (dtype(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev]) == Node#t);
	assume 1 > 0;
	assume unfoldingMask#_32_$_1 == unfoldingMask#_32_$_0[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev := unfoldingMask#_32_$_0[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev][perm$N := unfoldingMask#_32_$_0[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev][perm$N] + 1]];
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_1,ZeroMask);
	assume IsGoodMask(unfoldingMask#_32_$_1);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_1,ZeroMask);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_1,ZeroMask);
	assume !(unfoldingHeap#_31_$_1[this,Node.prev] == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_1,ZeroMask);
	assume (unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.next] == null) || (dtype(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.next]) == Node#t);
	assume 1 > 0;
	assume unfoldingMask#_32_$_2 == unfoldingMask#_32_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.next := unfoldingMask#_32_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.next][perm$N := unfoldingMask#_32_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.next][perm$N] + 1]];
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_2,ZeroMask);
	assume IsGoodMask(unfoldingMask#_32_$_2);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.next]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_2,ZeroMask);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_2,ZeroMask);
	assume !(unfoldingHeap#_31_$_1[this,Node.prev] == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_2,ZeroMask);
	assume true;
	assume 1 > 0;
	assume unfoldingMask#_32_$_3 == unfoldingMask#_32_$_2[unfoldingHeap#_31_$_1[this,Node.prev],mu := unfoldingMask#_32_$_2[unfoldingHeap#_31_$_1[this,Node.prev],mu][perm$N := unfoldingMask#_32_$_2[unfoldingHeap#_31_$_1[this,Node.prev],mu][perm$N] + 1]];
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_3,ZeroMask);
	assume IsGoodMask(unfoldingMask#_32_$_3);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],mu]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_3,ZeroMask);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_3,ZeroMask);
	if ($_$_condition_$2) { goto anon114_Then; } else { goto anon114_Else; }
anon114_Then:
	assume !(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev] == null);
	assume !(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev] == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_3,ZeroMask);
	assume Fractions(100) > 0;
	assume unfoldingMask#_32_$_4 == unfoldingMask#_32_$_3[unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev],Node.invLeft := unfoldingMask#_32_$_3[unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev],Node.invLeft][perm$R := unfoldingMask#_32_$_3[unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev],Node.invLeft][perm$R] + Fractions(100)]];
	assume IsGoodMask(unfoldingMask#_32_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev],Node.invLeft]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,ZeroMask);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,ZeroMask);
	assume predRec#_48_$_0 == Heap[Heap[this,Node.prev],Node.prev];
	assume #Node.invLeft#trigger(Heap[Heap[this,Node.prev],Node.prev]);
	assume predVer#_49_$_0 == unfoldingHeap#_31_$_1[Heap[Heap[this,Node.prev],Node.prev],Node.invLeft];
	if ($_$_condition_$3) { goto anon115_Then; } else { goto anon115_Else; }
anon114_Else:
	assume unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev] == null;
	assume unfoldingMask#_32_$_5 == unfoldingMask#_32_$_3;
	assume unfoldingSecMask#_33_$_5 == ZeroMask;
	goto anon35;
anon115_Then:
	assume false;
	goto $exit;
anon115_Else:
	assume !false;
	assume !(predRec#_48_$_0 == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,ZeroMask);
	assume (unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev] == null) || (dtype(unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev]) == Node#t);
	assume 1 > 0;
	assume unfoldingSecMask#_33_$_0 == ZeroMask[predRec#_48_$_0,Node.prev := ZeroMask[predRec#_48_$_0,Node.prev][perm$N := ZeroMask[predRec#_48_$_0,Node.prev][perm$N] + 1]];
	assume wf(unfoldingHeap#_31_$_1,unfoldingSecMask#_33_$_0,unfoldingSecMask#_33_$_0);
	assume IsGoodMask(unfoldingMask#_32_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_0);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_0);
	assume !(predRec#_48_$_0 == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_0);
	assume (unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.next] == null) || (dtype(unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.next]) == Node#t);
	assume 1 > 0;
	assume unfoldingSecMask#_33_$_1 == unfoldingSecMask#_33_$_0[predRec#_48_$_0,Node.next := unfoldingSecMask#_33_$_0[predRec#_48_$_0,Node.next][perm$N := unfoldingSecMask#_33_$_0[predRec#_48_$_0,Node.next][perm$N] + 1]];
	assume wf(unfoldingHeap#_31_$_1,unfoldingSecMask#_33_$_1,unfoldingSecMask#_33_$_1);
	assume IsGoodMask(unfoldingMask#_32_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.next]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_1);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_1);
	assume !(predRec#_48_$_0 == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_1);
	assume true;
	assume 1 > 0;
	assume unfoldingSecMask#_33_$_2 == unfoldingSecMask#_33_$_1[predRec#_48_$_0,mu := unfoldingSecMask#_33_$_1[predRec#_48_$_0,mu][perm$N := unfoldingSecMask#_33_$_1[predRec#_48_$_0,mu][perm$N] + 1]];
	assume wf(unfoldingHeap#_31_$_1,unfoldingSecMask#_33_$_2,unfoldingSecMask#_33_$_2);
	assume IsGoodMask(unfoldingMask#_32_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[predRec#_48_$_0,mu]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_2);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_2);
	if ($_$_condition_$4) { goto anon122_Then; } else { goto anon122_Else; }
anon35:
	assume IsGoodMask(unfoldingMask#_32_$_5);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_5,unfoldingSecMask#_33_$_5);
	if ($_$_condition_$5) { goto anon123_Then; } else { goto anon123_Else; }
anon122_Then:
	assume !(unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev] == null);
	assume !(unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev] == null);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_2);
	assume Fractions(100) > 0;
	assume unfoldingSecMask#_33_$_3 == unfoldingSecMask#_33_$_2[unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev],Node.invLeft := unfoldingSecMask#_33_$_2[unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev],Node.invLeft][perm$R := unfoldingSecMask#_33_$_2[unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev],Node.invLeft][perm$R] + Fractions(100)]];
	assume IsGoodMask(unfoldingMask#_32_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev],Node.invLeft]));
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_3);
	assume wf(unfoldingHeap#_31_$_1,unfoldingMask#_32_$_4,unfoldingSecMask#_33_$_3);
	assume unfoldingSecMask#_33_$_4 == unfoldingSecMask#_33_$_3;
	goto anon34;
anon122_Else:
	assume unfoldingHeap#_31_$_1[predRec#_48_$_0,Node.prev] == null;
	assume unfoldingSecMask#_33_$_4 == unfoldingSecMask#_33_$_2;
	goto anon34;
anon34:
	assume MuBelow(unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],Node.prev],mu],unfoldingHeap#_31_$_1[unfoldingHeap#_31_$_1[this,Node.prev],mu]);
	assume unfoldingMask#_32_$_5 == unfoldingMask#_32_$_4;
	assume unfoldingSecMask#_33_$_5 == unfoldingSecMask#_33_$_4;
	goto anon35;
anon123_Then:
	assume false;
	goto $exit;
anon123_Else:
	assume !false;
	assume !(Heap[this,Node.prev] == null);
	assume wf(Heap,Mask_$_3,ZeroMask);
	assume (Heap[Heap[this,Node.prev],Node.prev] == null) || (dtype(Heap[Heap[this,Node.prev],Node.prev]) == Node#t);
	assume 1 > 0;
	assume SecMask_$_0 == ZeroMask[Heap[this,Node.prev],Node.prev := ZeroMask[Heap[this,Node.prev],Node.prev][perm$N := ZeroMask[Heap[this,Node.prev],Node.prev][perm$N] + 1]];
	assume wf(Heap,SecMask_$_0,SecMask_$_0);
	assume IsGoodMask(Mask_$_3);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.prev],Node.prev]));
	assume wf(Heap,Mask_$_3,SecMask_$_0);
	assume wf(Heap,Mask_$_3,SecMask_$_0);
	assume !(Heap[this,Node.prev] == null);
	assume wf(Heap,Mask_$_3,SecMask_$_0);
	assume (Heap[Heap[this,Node.prev],Node.next] == null) || (dtype(Heap[Heap[this,Node.prev],Node.next]) == Node#t);
	assume 1 > 0;
	assume SecMask_$_1 == SecMask_$_0[Heap[this,Node.prev],Node.next := SecMask_$_0[Heap[this,Node.prev],Node.next][perm$N := SecMask_$_0[Heap[this,Node.prev],Node.next][perm$N] + 1]];
	assume wf(Heap,SecMask_$_1,SecMask_$_1);
	assume IsGoodMask(Mask_$_3);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.prev],Node.next]));
	assume wf(Heap,Mask_$_3,SecMask_$_1);
	assume wf(Heap,Mask_$_3,SecMask_$_1);
	assume !(Heap[this,Node.prev] == null);
	assume wf(Heap,Mask_$_3,SecMask_$_1);
	assume true;
	assume 1 > 0;
	assume SecMask_$_2 == SecMask_$_1[Heap[this,Node.prev],mu := SecMask_$_1[Heap[this,Node.prev],mu][perm$N := SecMask_$_1[Heap[this,Node.prev],mu][perm$N] + 1]];
	assume wf(Heap,SecMask_$_2,SecMask_$_2);
	assume IsGoodMask(Mask_$_3);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.prev],mu]));
	assume wf(Heap,Mask_$_3,SecMask_$_2);
	assume wf(Heap,Mask_$_3,SecMask_$_2);
	if ($_$_condition_$6) { goto anon130_Then; } else { goto anon130_Else; }
anon130_Then:
	assume !(Heap[Heap[this,Node.prev],Node.prev] == null);
	assume !(Heap[Heap[this,Node.prev],Node.prev] == null);
	assume wf(Heap,Mask_$_3,SecMask_$_2);
	assume Fractions(100) > 0;
	assume SecMask_$_3 == SecMask_$_2[Heap[Heap[this,Node.prev],Node.prev],Node.invLeft := SecMask_$_2[Heap[Heap[this,Node.prev],Node.prev],Node.invLeft][perm$R := SecMask_$_2[Heap[Heap[this,Node.prev],Node.prev],Node.invLeft][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_3);
	assume IsGoodState(heapFragment(Heap[Heap[Heap[this,Node.prev],Node.prev],Node.invLeft]));
	assume wf(Heap,Mask_$_3,SecMask_$_3);
	assume wf(Heap,Mask_$_3,SecMask_$_3);
	assume SecMask_$_4 == SecMask_$_3;
	goto anon51;
anon130_Else:
	assume Heap[Heap[this,Node.prev],Node.prev] == null;
	assume SecMask_$_4 == SecMask_$_2;
	goto anon51;
anon51:
	assert { :msg "  18.67: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  18.67: Location might not be readable." } true ==> CanRead(unfoldingMask#_32_$_5,unfoldingSecMask#_33_$_5,this,Node.prev);
	assert { :msg "  18.67: Receiver might be null." } true ==> (!(unfoldingHeap#_31_$_1[this,Node.prev] == null));
	assert { :msg "  18.67: Location might not be readable." } true ==> CanRead(unfoldingMask#_32_$_5,unfoldingSecMask#_33_$_5,unfoldingHeap#_31_$_1[this,Node.prev],mu);
	assert { :msg "  18.78: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  18.78: Location might not be readable." } true ==> CanRead(unfoldingMask#_32_$_5,unfoldingSecMask#_33_$_5,this,mu);
	assume MuBelow(Heap[Heap[this,Node.prev],mu],Heap[this,mu]);
	assume Mask_$_4 == Mask_$_3;
	assume SecMask_$_5 == SecMask_$_4;
	goto anon52;
anon131_Then:
	assume !(Heap[this,Node.next] == null);
	assert { :msg "  19.25: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  19.25: Location might not be readable." } true ==> CanRead(Mask_$_4,SecMask_$_5,this,Node.next);
	assert { :msg "  19.25: Receiver might be null." } !(Heap[this,Node.next] == null);
	assert { :msg "  19.25: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  19.25: Location might not be readable." } true ==> CanRead(Mask_$_4,SecMask_$_5,this,Node.next);
	assume !(Heap[this,Node.next] == null);
	assume wf(Heap,Mask_$_4,SecMask_$_5);
	assume Fractions(100) > 0;
	assume Mask_$_5 == Mask_$_4[Heap[this,Node.next],Node.invRight := Mask_$_4[Heap[this,Node.next],Node.invRight][perm$R := Mask_$_4[Heap[this,Node.next],Node.invRight][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_5);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.next],Node.invRight]));
	assume wf(Heap,Mask_$_5,SecMask_$_5);
	assume wf(Heap,Mask_$_5,SecMask_$_5);
	assume predRec#_63_$_0 == Heap[this,Node.next];
	assume #Node.invRight#trigger(Heap[this,Node.next]);
	assume predVer#_64_$_0 == Heap[Heap[this,Node.next],Node.invRight];
	assume (0 < unfoldingK#_71) && ((1000 * unfoldingK#_71) < Fractions(1));
	assert { :msg "  19.52: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  19.52: Location might not be readable." } true ==> CanRead(Mask_$_5,SecMask_$_5,this,Node.next);
	assert { :msg "  19.52: Receiver might be null." } true ==> (!(Heap[this,Node.next] == null));
	assume wf(Heap,Mask_$_5,SecMask_$_5);
	assert { :msg "  19.42: Unfolding might fail. The permission at 19.52 might not be positive." } Fractions(100) > 0;
	assert { :msg "  19.42: Unfolding might fail. Insufficient fraction at 19.52 for Node.invRight." } (Fractions(100) <= Mask_$_5[Heap[this,Node.next],Node.invRight][perm$R]) && ((Fractions(100) == Mask_$_5[Heap[this,Node.next],Node.invRight][perm$R]) ==> (0 <= Mask_$_5[Heap[this,Node.next],Node.invRight][perm$N]));
	assume unfoldingMask#_67_$_0 == Mask_$_5[Heap[this,Node.next],Node.invRight := Mask_$_5[Heap[this,Node.next],Node.invRight][perm$R := Mask_$_5[Heap[this,Node.next],Node.invRight][perm$R] - Fractions(100)]];
	if ($_$_condition_$8) { goto anon132_Then; } else { goto anon132_Else; }
anon131_Else:
	assume Heap[this,Node.next] == null;
	assume SecMask_$_11 == SecMask_$_5;
	assume Mask_$_6 == Mask_$_4;
	goto anon104;
anon132_Then:
	assume false;
	goto $exit;
anon132_Else:
	assume !false;
	if ($_$_condition_$9) { goto anon139_Then; } else { goto anon139_Else; }
anon104:
	assume IsGoodMask(Mask_$_6);
	assume wf(Heap,Mask_$_6,SecMask_$_11);
	assert { :msg "  16.5: SMOKE-TEST-51. (Predicate Node.inv is equivalent to false.)" } !(1 == 1);
	goto $exit;
anon139_Then:
	assume !CanRead(unfoldingMask#_67_$_0,SecMask_$_5,Heap[this,Node.next],Node.invRight);
	assume oldVers#_81_$_0 == Heap[Heap[this,Node.next],Node.invRight];
	assume unfoldingHeap#_66_$_0 == Heap[Heap[this,Node.next],Node.invRight := newVers#_82_$_0];
	assume oldVers#_81_$_0 < unfoldingHeap#_66_$_0[unfoldingHeap#_66_$_0[this,Node.next],Node.invRight];
	assume unfoldingHeap#_66_$_1 == unfoldingHeap#_66_$_0;
	goto anon69;
anon139_Else:
	assume CanRead(unfoldingMask#_67_$_0,SecMask_$_5,Heap[this,Node.next],Node.invRight);
	assume unfoldingHeap#_66_$_1 == Heap;
	goto anon69;
anon69:
	assume IsGoodMask(unfoldingMask#_67_$_0);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_0,SecMask_$_5);
	assume IsGoodMask(unfoldingMask#_67_$_0);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_0,SecMask_$_5);
	assume !(unfoldingHeap#_66_$_1[this,Node.next] == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_0,SecMask_$_5);
	assume (unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.prev] == null) || (dtype(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.prev]) == Node#t);
	assume 1 > 0;
	assume unfoldingMask#_67_$_1 == unfoldingMask#_67_$_0[unfoldingHeap#_66_$_1[this,Node.next],Node.prev := unfoldingMask#_67_$_0[unfoldingHeap#_66_$_1[this,Node.next],Node.prev][perm$N := unfoldingMask#_67_$_0[unfoldingHeap#_66_$_1[this,Node.next],Node.prev][perm$N] + 1]];
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_1,SecMask_$_5);
	assume IsGoodMask(unfoldingMask#_67_$_1);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.prev]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_1,SecMask_$_5);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_1,SecMask_$_5);
	assume !(unfoldingHeap#_66_$_1[this,Node.next] == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_1,SecMask_$_5);
	assume (unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next] == null) || (dtype(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next]) == Node#t);
	assume 1 > 0;
	assume unfoldingMask#_67_$_2 == unfoldingMask#_67_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next := unfoldingMask#_67_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next][perm$N := unfoldingMask#_67_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next][perm$N] + 1]];
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_2,SecMask_$_5);
	assume IsGoodMask(unfoldingMask#_67_$_2);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_2,SecMask_$_5);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_2,SecMask_$_5);
	assume !(unfoldingHeap#_66_$_1[this,Node.next] == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_2,SecMask_$_5);
	assume true;
	assume 1 > 0;
	assume unfoldingMask#_67_$_3 == unfoldingMask#_67_$_2[unfoldingHeap#_66_$_1[this,Node.next],mu := unfoldingMask#_67_$_2[unfoldingHeap#_66_$_1[this,Node.next],mu][perm$N := unfoldingMask#_67_$_2[unfoldingHeap#_66_$_1[this,Node.next],mu][perm$N] + 1]];
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_3,SecMask_$_5);
	assume IsGoodMask(unfoldingMask#_67_$_3);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],mu]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_3,SecMask_$_5);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_3,SecMask_$_5);
	if ($_$_condition_$10) { goto anon140_Then; } else { goto anon140_Else; }
anon140_Then:
	assume !(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next] == null);
	assume !(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next] == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_3,SecMask_$_5);
	assume Fractions(100) > 0;
	assume unfoldingMask#_67_$_4 == unfoldingMask#_67_$_3[unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next],Node.invRight := unfoldingMask#_67_$_3[unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next],Node.invRight][perm$R := unfoldingMask#_67_$_3[unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next],Node.invRight][perm$R] + Fractions(100)]];
	assume IsGoodMask(unfoldingMask#_67_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next],Node.invRight]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,SecMask_$_5);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,SecMask_$_5);
	assume predRec#_83_$_0 == Heap[Heap[this,Node.next],Node.next];
	assume #Node.invRight#trigger(Heap[Heap[this,Node.next],Node.next]);
	assume predVer#_84_$_0 == unfoldingHeap#_66_$_1[Heap[Heap[this,Node.next],Node.next],Node.invRight];
	if ($_$_condition_$11) { goto anon141_Then; } else { goto anon141_Else; }
anon140_Else:
	assume unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next] == null;
	assume unfoldingMask#_67_$_5 == unfoldingMask#_67_$_3;
	assume unfoldingSecMask#_68_$_5 == SecMask_$_5;
	goto anon87;
anon141_Then:
	assume false;
	goto $exit;
anon141_Else:
	assume !false;
	assume !(predRec#_83_$_0 == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,SecMask_$_5);
	assume (unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.prev] == null) || (dtype(unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.prev]) == Node#t);
	assume 1 > 0;
	assume unfoldingSecMask#_68_$_0 == SecMask_$_5[predRec#_83_$_0,Node.prev := SecMask_$_5[predRec#_83_$_0,Node.prev][perm$N := SecMask_$_5[predRec#_83_$_0,Node.prev][perm$N] + 1]];
	assume wf(unfoldingHeap#_66_$_1,unfoldingSecMask#_68_$_0,unfoldingSecMask#_68_$_0);
	assume IsGoodMask(unfoldingMask#_67_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.prev]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_0);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_0);
	assume !(predRec#_83_$_0 == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_0);
	assume (unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next] == null) || (dtype(unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next]) == Node#t);
	assume 1 > 0;
	assume unfoldingSecMask#_68_$_1 == unfoldingSecMask#_68_$_0[predRec#_83_$_0,Node.next := unfoldingSecMask#_68_$_0[predRec#_83_$_0,Node.next][perm$N := unfoldingSecMask#_68_$_0[predRec#_83_$_0,Node.next][perm$N] + 1]];
	assume wf(unfoldingHeap#_66_$_1,unfoldingSecMask#_68_$_1,unfoldingSecMask#_68_$_1);
	assume IsGoodMask(unfoldingMask#_67_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_1);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_1);
	assume !(predRec#_83_$_0 == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_1);
	assume true;
	assume 1 > 0;
	assume unfoldingSecMask#_68_$_2 == unfoldingSecMask#_68_$_1[predRec#_83_$_0,mu := unfoldingSecMask#_68_$_1[predRec#_83_$_0,mu][perm$N := unfoldingSecMask#_68_$_1[predRec#_83_$_0,mu][perm$N] + 1]];
	assume wf(unfoldingHeap#_66_$_1,unfoldingSecMask#_68_$_2,unfoldingSecMask#_68_$_2);
	assume IsGoodMask(unfoldingMask#_67_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[predRec#_83_$_0,mu]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_2);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_2);
	if ($_$_condition_$12) { goto anon148_Then; } else { goto anon148_Else; }
anon87:
	assume IsGoodMask(unfoldingMask#_67_$_5);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_5,unfoldingSecMask#_68_$_5);
	if ($_$_condition_$13) { goto anon149_Then; } else { goto anon149_Else; }
anon148_Then:
	assume !(unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next] == null);
	assume !(unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next] == null);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_2);
	assume Fractions(100) > 0;
	assume unfoldingSecMask#_68_$_3 == unfoldingSecMask#_68_$_2[unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next],Node.invRight := unfoldingSecMask#_68_$_2[unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next],Node.invRight][perm$R := unfoldingSecMask#_68_$_2[unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next],Node.invRight][perm$R] + Fractions(100)]];
	assume IsGoodMask(unfoldingMask#_67_$_4);
	assume IsGoodState(heapFragment(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next],Node.invRight]));
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_3);
	assume wf(unfoldingHeap#_66_$_1,unfoldingMask#_67_$_4,unfoldingSecMask#_68_$_3);
	assume unfoldingSecMask#_68_$_4 == unfoldingSecMask#_68_$_3;
	goto anon86;
anon148_Else:
	assume unfoldingHeap#_66_$_1[predRec#_83_$_0,Node.next] == null;
	assume unfoldingSecMask#_68_$_4 == unfoldingSecMask#_68_$_2;
	goto anon86;
anon86:
	assume MuBelow(unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],mu],unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[unfoldingHeap#_66_$_1[this,Node.next],Node.next],mu]);
	assume unfoldingMask#_67_$_5 == unfoldingMask#_67_$_4;
	assume unfoldingSecMask#_68_$_5 == unfoldingSecMask#_68_$_4;
	goto anon87;
anon149_Then:
	assume false;
	goto $exit;
anon149_Else:
	assume !false;
	assume !(Heap[this,Node.next] == null);
	assume wf(Heap,Mask_$_5,SecMask_$_5);
	assume (Heap[Heap[this,Node.next],Node.prev] == null) || (dtype(Heap[Heap[this,Node.next],Node.prev]) == Node#t);
	assume 1 > 0;
	assume SecMask_$_6 == SecMask_$_5[Heap[this,Node.next],Node.prev := SecMask_$_5[Heap[this,Node.next],Node.prev][perm$N := SecMask_$_5[Heap[this,Node.next],Node.prev][perm$N] + 1]];
	assume wf(Heap,SecMask_$_6,SecMask_$_6);
	assume IsGoodMask(Mask_$_5);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.next],Node.prev]));
	assume wf(Heap,Mask_$_5,SecMask_$_6);
	assume wf(Heap,Mask_$_5,SecMask_$_6);
	assume !(Heap[this,Node.next] == null);
	assume wf(Heap,Mask_$_5,SecMask_$_6);
	assume (Heap[Heap[this,Node.next],Node.next] == null) || (dtype(Heap[Heap[this,Node.next],Node.next]) == Node#t);
	assume 1 > 0;
	assume SecMask_$_7 == SecMask_$_6[Heap[this,Node.next],Node.next := SecMask_$_6[Heap[this,Node.next],Node.next][perm$N := SecMask_$_6[Heap[this,Node.next],Node.next][perm$N] + 1]];
	assume wf(Heap,SecMask_$_7,SecMask_$_7);
	assume IsGoodMask(Mask_$_5);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.next],Node.next]));
	assume wf(Heap,Mask_$_5,SecMask_$_7);
	assume wf(Heap,Mask_$_5,SecMask_$_7);
	assume !(Heap[this,Node.next] == null);
	assume wf(Heap,Mask_$_5,SecMask_$_7);
	assume true;
	assume 1 > 0;
	assume SecMask_$_8 == SecMask_$_7[Heap[this,Node.next],mu := SecMask_$_7[Heap[this,Node.next],mu][perm$N := SecMask_$_7[Heap[this,Node.next],mu][perm$N] + 1]];
	assume wf(Heap,SecMask_$_8,SecMask_$_8);
	assume IsGoodMask(Mask_$_5);
	assume IsGoodState(heapFragment(Heap[Heap[this,Node.next],mu]));
	assume wf(Heap,Mask_$_5,SecMask_$_8);
	assume wf(Heap,Mask_$_5,SecMask_$_8);
	if ($_$_condition_$14) { goto anon156_Then; } else { goto anon156_Else; }
anon156_Then:
	assume !(Heap[Heap[this,Node.next],Node.next] == null);
	assume !(Heap[Heap[this,Node.next],Node.next] == null);
	assume wf(Heap,Mask_$_5,SecMask_$_8);
	assume Fractions(100) > 0;
	assume SecMask_$_9 == SecMask_$_8[Heap[Heap[this,Node.next],Node.next],Node.invRight := SecMask_$_8[Heap[Heap[this,Node.next],Node.next],Node.invRight][perm$R := SecMask_$_8[Heap[Heap[this,Node.next],Node.next],Node.invRight][perm$R] + Fractions(100)]];
	assume IsGoodMask(Mask_$_5);
	assume IsGoodState(heapFragment(Heap[Heap[Heap[this,Node.next],Node.next],Node.invRight]));
	assume wf(Heap,Mask_$_5,SecMask_$_9);
	assume wf(Heap,Mask_$_5,SecMask_$_9);
	assume SecMask_$_10 == SecMask_$_9;
	goto anon103;
anon156_Else:
	assume Heap[Heap[this,Node.next],Node.next] == null;
	assume SecMask_$_10 == SecMask_$_8;
	goto anon103;
anon103:
	assert { :msg "  19.69: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  19.69: Location might not be readable." } true ==> CanRead(unfoldingMask#_67_$_5,unfoldingSecMask#_68_$_5,this,mu);
	assert { :msg "  19.80: Receiver might be null." } true ==> (!(this == null));
	assert { :msg "  19.80: Location might not be readable." } true ==> CanRead(unfoldingMask#_67_$_5,unfoldingSecMask#_68_$_5,this,Node.next);
	assert { :msg "  19.80: Receiver might be null." } true ==> (!(unfoldingHeap#_66_$_1[this,Node.next] == null));
	assert { :msg "  19.80: Location might not be readable." } true ==> CanRead(unfoldingMask#_67_$_5,unfoldingSecMask#_68_$_5,unfoldingHeap#_66_$_1[this,Node.next],mu);
	assume MuBelow(Heap[this,mu],Heap[Heap[this,Node.next],mu]);
	assume SecMask_$_11 == SecMask_$_10;
	assume Mask_$_6 == Mask_$_5;
	goto anon104;
}
